### ISSUE TITLE
Does not compile on io.js 3.0.0

### ISSUE THREAD

**Issue by vsimonian** [quartzjer/ursa#102]
Looks like it's related to some changes in V8.

```text
> ursa@0.8.5 install /home/vartan/GitHub/anvilresearch/connect/node_modules/ursa
> node-gyp rebuild

make: Entering directory '/home/vartan/GitHub/anvilresearch/connect/node_modules/ursa/build'
  CXX(target) Release/obj.target/ursaNative/src/ursaNative.o
In file included from ../src/ursaNative.h:10:0,
                 from ../src/ursaNative.cc:3:
../node_modules/nan/nan.h:324:27: error: redefinition of ‘template<class T> v8::Local<T> Nan::imp::NanEnsureHandleOrPersistent(const v8::Local<T>&)’
   NAN_INLINE v8::Local<T> NanEnsureHandleOrPersistent(const v8::Local<T> &val) {
                           ^
../node_modules/nan/nan.h:319:17: note: ‘template<class T> v8::Handle<T> Nan::imp::NanEnsureHandleOrPersistent(v8::Handle<T>&)’ previously declared here
   v8::Handle<T> NanEnsureHandleOrPersistent(const v8::Handle<T> &val) {
                 ^
../node_modules/nan/nan.h:344:27: error: redefinition of ‘template<class T> v8::Local<T> Nan::imp::NanEnsureLocal(v8::Handle<T>&)’
   NAN_INLINE v8::Local<T> NanEnsureLocal(const v8::Handle<T> &val) {
                           ^
../node_modules/nan/nan.h:334:27: note: ‘template<class T> v8::Local<T> Nan::imp::NanEnsureLocal(const v8::Local<T>&)’ previously declared here
   NAN_INLINE v8::Local<T> NanEnsureLocal(const v8::Local<T> &val) {
                           ^
../node_modules/nan/nan.h:757:13: error: ‘node::smalloc’ has not been declared
     , node::smalloc::FreeCallback callback
             ^
../node_modules/nan/nan.h:757:35: error: expected ‘,’ or ‘...’ before ‘callback’
     , node::smalloc::FreeCallback callback
                                   ^
../node_modules/nan/nan.h: In function ‘v8::Local<v8::Object> NanNewBufferHandle(char*, size_t, int)’:
../node_modules/nan/nan.h:761:50: error: ‘callback’ was not declared in this scope
         v8::Isolate::GetCurrent(), data, length, callback, hint);
                                                  ^
../node_modules/nan/nan.h:761:60: error: ‘hint’ was not declared in this scope
         v8::Isolate::GetCurrent(), data, length, callback, hint);
                                                            ^
../node_modules/nan/nan.h: In function ‘v8::Local<v8::Object> NanNewBufferHandle(const char*, uint32_t)’:
../node_modules/nan/nan.h:768:67: error: call of overloaded ‘New(v8::Isolate*, const char*&, uint32_t&)’ is ambiguous
     return node::Buffer::New(v8::Isolate::GetCurrent(), data, size);
                                                                   ^
../node_modules/nan/nan.h:768:67: note: candidates are:
In file included from ../node_modules/nan/nan.h:25:0,
                 from ../src/ursaNative.h:10,
                 from ../src/ursaNative.cc:3:
/home/vartan/.node-gyp/3.0.0/include/node/node_buffer.h:35:40: note: v8::MaybeLocal<v8::Object> node::Buffer::New(v8::Isolate*, v8::Handle<v8::String>, node::encoding) <near match>
 NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                        ^
/home/vartan/.node-gyp/3.0.0/include/node/node_buffer.h:35:40: note:   no known conversion for argument 3 from ‘uint32_t {aka unsigned int}’ to ‘node::encoding’
/home/vartan/.node-gyp/3.0.0/include/node/node_buffer.h:47:40: note: v8::MaybeLocal<v8::Object> node::Buffer::New(v8::Isolate*, char*, size_t) <near match>
 NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                        ^
/home/vartan/.node-gyp/3.0.0/include/node/node_buffer.h:47:40: note:   no known conversion for argument 2 from ‘const char*’ to ‘char*’
In file included from ../src/ursaNative.h:10:0,
                 from ../src/ursaNative.cc:3:
../node_modules/nan/nan.h: In function ‘v8::Local<v8::Object> NanNewBufferHandle(uint32_t)’:
../node_modules/nan/nan.h:772:61: error: could not convert ‘node::Buffer::New(v8::Isolate::GetCurrent(), ((size_t)size))’ from ‘v8::MaybeLocal<v8::Object>’ to ‘v8::Local<v8::Object>’
     return node::Buffer::New(v8::Isolate::GetCurrent(), size);
                                                             ^
../node_modules/nan/nan.h: In function ‘v8::Local<v8::Object> NanBufferUse(char*, uint32_t)’:
../node_modules/nan/nan.h:779:12: error: ‘Use’ is not a member of ‘node::Buffer’
     return node::Buffer::Use(v8::Isolate::GetCurrent(), data, size);
            ^
../node_modules/nan/nan.h: In function ‘v8::Local<v8::Object> NanNewBufferHandle(uint32_t)’:
../node_modules/nan/nan.h:773:3: warning: control reaches end of non-void function [-Wreturn-type]
   }
   ^
ursaNative.target.mk:93: recipe for target 'Release/obj.target/ursaNative/src/ursaNative.o' failed
make: *** [Release/obj.target/ursaNative/src/ursaNative.o] Error 1
make: Leaving directory '/home/vartan/GitHub/anvilresearch/connect/node_modules/ursa/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 3.19.0-25-generic
gyp ERR! command "/usr/bin/iojs" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/vartan/GitHub/anvilresearch/connect/node_modules/ursa
gyp ERR! node -v v3.0.0
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok
```

**Comment by caiges** [comment]
Confirming this is happening with the new Node version (4.0.0) as well.

**Comment by mattkrea** [comment]
FWIW here is some console output with an updated `nan` module:

```
Ξ Node/ursa git:(master) ▶ node-gyp rebuild
gyp info it worked if it ends with ok
gyp info using node-gyp@3.0.1
gyp info using node@4.0.0 | darwin | x64
gyp info spawn python
gyp info spawn args [ '/usr/local/lib/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/matt/Documents/Development/Node/ursa/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/local/lib/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/matt/.node-gyp/4.0.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/matt/.node-gyp/4.0.0',
gyp info spawn args   '-Dnode_gyp_dir=/usr/local/lib/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/matt/Documents/Development/Node/ursa',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
  CXX(target) Release/obj.target/ursaNative/src/ursaNative.o
../src/ursaNative.cc:52:5: error: use of undeclared identifier 'NanNew'
    BIND(target, textToNid, TextToNid);
    ^
../src/ursaNative.cc:35:18: note: expanded from macro 'BIND'
    (proto)->Set(NanNew<String>(#highName), \
                 ^
../src/ursaNative.cc:52:5: error: 'String' does not refer to a value
    BIND(target, textToNid, TextToNid);
    ^
../src/ursaNative.cc:35:25: note: expanded from macro 'BIND'
    (proto)->Set(NanNew<String>(#highName), \
                        ^
/Users/matt/.node-gyp/4.0.0/include/node/v8.h:2081:17: note: declared here
class V8_EXPORT String : public Name {
                ^
../src/ursaNative.cc:52:5: error: use of undeclared identifier 'NanNew'
    BIND(target, textToNid, TextToNid);
    ^
../src/ursaNative.cc:36:9: note: expanded from macro 'BIND'
        NanNew<FunctionTemplate>(lowName)->GetFunction())
        ^
../src/ursaNative.cc:52:5: error: 'FunctionTemplate' does not refer to a value
    BIND(target, textToNid, TextToNid);
    ^
../src/ursaNative.cc:36:16: note: expanded from macro 'BIND'
        NanNew<FunctionTemplate>(lowName)->GetFunction())
               ^
/Users/matt/.node-gyp/4.0.0/include/node/v8.h:4346:17: note: declared here
class V8_EXPORT FunctionTemplate : public Template {
                ^
../src/ursaNative.cc:52:5: error: member reference base type 'Nan::NAN_METHOD_RETURN_TYPE (Nan::NAN_METHOD_ARGS_TYPE)'
      is not a structure or union
    BIND(target, textToNid, TextToNid);
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../src/ursaNative.cc:36:42: note: expanded from macro 'BIND'
        NanNew<FunctionTemplate>(lowName)->GetFunction())
                                ~~~~~~~~~^ ~~~~~~~~~~~
../src/ursaNative.cc:82:5: error: use of undeclared identifier 'NanThrowError'; did you mean 'Nan::ThrowError'?
    NanThrowError(err);
    ^~~~~~~~~~~~~
    Nan::ThrowError
../node_modules/nan/nan.h:639:3: note: 'Nan::ThrowError' declared here
  X(Error)
  ^
../node_modules/nan/nan.h:627:21: note: expanded from macro 'X'
    NAN_INLINE void Throw ## NAME(const char *msg) {                           \
                    ^
<scratch space>:108:1: note: expanded from here
ThrowError
^
../src/ursaNative.cc:91:5: error: use of undeclared identifier 'NanThrowError'; did you mean 'Nan::ThrowError'?
    NanThrowError("Allocation failed.");
    ^~~~~~~~~~~~~
    Nan::ThrowError
../node_modules/nan/nan.h:639:3: note: 'Nan::ThrowError' declared here
  X(Error)
  ^
../node_modules/nan/nan.h:627:21: note: expanded from macro 'X'
    NAN_INLINE void Throw ## NAME(const char *msg) {                           \
                    ^
<scratch space>:108:1: note: expanded from here
ThrowError
^
../src/ursaNative.cc:101:28: error: use of undeclared identifier 'NanNewBufferHandle'
    Local<Object> result = NanNewBufferHandle(length);
                           ^
../src/ursaNative.cc:105:16: error: use of undeclared identifier 'NanUndefined'; did you mean 'Nan::Undefined'?
        return NanUndefined();
               ^~~~~~~~~~~~
               Nan::Undefined
../node_modules/nan/nan.h:509:39: note: 'Nan::Undefined' declared here
  NAN_INLINE v8::Local<v8::Primitive> Undefined() {
                                      ^
../src/ursaNative.cc:122:16: error: use of undeclared identifier 'NanUndefined'; did you mean 'Nan::Undefined'?
        return NanUndefined();
               ^~~~~~~~~~~~
               Nan::Undefined
../node_modules/nan/nan.h:509:39: note: 'Nan::Undefined' declared here
  NAN_INLINE v8::Local<v8::Primitive> Undefined() {
                                      ^
../src/ursaNative.cc:127:28: error: use of undeclared identifier 'NanNewBufferHandle'
    Local<Object> result = NanNewBufferHandle(length);
                           ^
../src/ursaNative.cc:132:16: error: use of undeclared identifier 'NanUndefined'; did you mean 'Nan::Undefined'?
        return NanUndefined();
               ^~~~~~~~~~~~
               Nan::Undefined
../node_modules/nan/nan.h:509:39: note: 'Nan::Undefined' declared here
  NAN_INLINE v8::Local<v8::Primitive> Undefined() {
                                      ^
../src/ursaNative.cc:148:9: error: use of undeclared identifier 'NanThrowError'; did you mean 'Nan::ThrowError'?
        NanThrowError("Expected a Buffer in args[0].");
        ^~~~~~~~~~~~~
        Nan::ThrowError
../node_modules/nan/nan.h:639:3: note: 'Nan::ThrowError' declared here
  X(Error)
  ^
../node_modules/nan/nan.h:627:21: note: expanded from macro 'X'
    NAN_INLINE void Throw ## NAME(const char *msg) {                           \
                    ^
<scratch space>:108:1: note: expanded from here
ThrowError
^
../src/ursaNative.cc:163:9: error: use of undeclared identifier 'NanThrowError'; did you mean 'Nan::ThrowError'?
        NanThrowError("Expected a Buffer.");
        ^~~~~~~~~~~~~
        Nan::ThrowError
../node_modules/nan/nan.h:639:3: note: 'Nan::ThrowError' declared here
  X(Error)
  ^
../node_modules/nan/nan.h:627:21: note: expanded from macro 'X'
    NAN_INLINE void Throw ## NAME(const char *msg) {                           \
                    ^
<scratch space>:108:1: note: expanded from here
ThrowError
^
../src/ursaNative.cc:218:9: error: use of undeclared identifier 'NanThrowError'; did you mean 'Nan::ThrowError'?
        NanThrowError(message);
        ^~~~~~~~~~~~~
        Nan::ThrowError
../node_modules/nan/nan.h:639:3: note: 'Nan::ThrowError' declared here
  X(Error)
  ^
../node_modules/nan/nan.h:627:21: note: expanded from macro 'X'
    NAN_INLINE void Throw ## NAME(const char *msg) {                           \
                    ^
<scratch space>:108:1: note: expanded from here
ThrowError
^
../src/ursaNative.cc:274:5: error: use of undeclared identifier 'NanScope'
    NanScope();
    ^
../src/ursaNative.cc:276:9: error: use of undeclared identifier 'args'; did you mean 'uv_process_options_s::args'?
    if (args.Length() < 1) {
        ^~~~
        uv_process_options_s::args
/Users/matt/.node-gyp/4.0.0/include/node/uv.h:862:10: note: 'uv_process_options_s::args' declared here
  char** args;
         ^
../src/ursaNative.cc:276:9: error: invalid use of non-static data member 'args'
    if (args.Length() < 1) {
        ^~~~
../src/ursaNative.cc:277:9: error: use of undeclared identifier 'NanThrowError'; did you mean 'Nan::ThrowError'?
        NanThrowError("Missing args[0].");
        ^~~~~~~~~~~~~
        Nan::ThrowError
../node_modules/nan/nan.h:639:3: note: 'Nan::ThrowError' declared here
  X(Error)
  ^
../node_modules/nan/nan.h:627:21: note: expanded from macro 'X'
    NAN_INLINE void Throw ## NAME(const char *msg) {                           \
                    ^
<scratch space>:108:1: note: expanded from here
ThrowError
^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make: *** [Release/obj.target/ursaNative/src/ursaNative.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 14.5.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/bin/node-gyp" "rebuild"
gyp ERR! cwd /Users/matt/Documents/Development/Node/ursa
gyp ERR! node -v v4.0.0
gyp ERR! node-gyp -v v3.0.1
gyp ERR! not ok
```

**Comment by mattkrea** [comment]
Adding to list on nodejs/node#2798

**Comment by mansona** [comment]
As I can see this it does compile from master so for the time being you can add `"ursa": "quartzjer/ursa"` to your package.json and it should work. 

The tests are not currently working as I mentioned in https://github.com/quartzjer/ursa/pull/105 . So I suspect the real work needs to be put into getting the tests up and running again and then getting a new release out the door for npm users

**Comment by mattkrea** [comment]
Ah thanks for pointing that out. I'll take a stab at it.

**Comment by adrai** [comment]
any updates?

**Comment by quartzjer** [comment]
@adrai ursa is effectively community supported at this point, I'm a bit behind on familiarity with compiled modules on the newer revs and won't have time to catch up in the near future, so hopefully someone else will be able to pick this up faster :)

**Comment by davedoesdev** [comment]
https://github.com/quartzjer/ursa/pull/107

**Comment by kelchy** [comment]
when will this be fixed?

**Comment by mgcrea** [comment]
@quartzjer looks like #107 fixes the failing tests, would be awesome if you could merge that and bump a major.

**Comment by quartzjer** [comment]
awesome! it's merged, if nothing crops up today I'll bump and publish a new rev, thanks!!

**Comment by adrai** [comment]
@quartzjer ok or nok? to release or not to release? this is the question ;-)

**Comment by mgcrea** [comment]
:+1:
