### ISSUE TITLE
Cannot install on Windows with node 0.12.7

### ISSUE THREAD

**Issue by rgmembreno** [quartzjer/ursa#103]
Hi all,

I have an issue installing Ursa 0.8.5 on my PC running Windows 7 SP1.  I recently upgraded to node 0.12.7, and when I tried to re-install my packages I got the following error from ursa:

error MSB4019: The imported project "C:\Microsoft.Cpp.Default.props" was not found
. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.
C:\Users\Travis\AppData\Roaming\npm\node_modules\karma\node_modules\socket.io\node_modules\socket.io-client\node_module
s\ws\build\validation.vcxproj(18,3): error MSB4019: The imported project "C:\Microsoft.Cpp.Default.props" was not found
. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.

More from the npm-debug.log:
457 verbose unsafe-perm in lifecycle true
458 info ursa@0.8.5 Failed to exec install script
459 verbose unlock done using <CWD>
460 verbose stack Error: ursa@0.8.5 install: `node-gyp rebuild`
460 verbose stack Exit status 1
460 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:213:16)
460 verbose stack     at EventEmitter.emit (events.js:110:17)
460 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:24:14)
460 verbose stack     at ChildProcess.emit (events.js:110:17)
460 verbose stack     at maybeClose (child_process.js:1015:16)
460 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
461 verbose pkgid ursa@0.8.5
462 verbose cwd <CWD>
463 error Windows_NT 6.1.7601
464 error argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "ursa"
465 error node v0.12.7
466 error npm  v2.11.3
467 error code ELIFECYCLE
468 error ursa@0.8.5 install: `node-gyp rebuild`
468 error Exit status 1
469 error Failed at the ursa@0.8.5 install script 'node-gyp rebuild'.
469 error This is most likely a problem with the ursa package,
469 error not with npm itself.
469 error Tell the author that this fails on your system:
469 error     node-gyp rebuild
469 error You can get their info via:
469 error     npm owner ls ursa
469 error There is likely additional logging output above.

I had no trouble building ursa when I used node 0.10.x.  My build setup is as follows:
node-gyp: 2.11.3
nan: 2.0.7
Visual Studio: 2013 Express for Desktop

**Comment by ashu-daffodil** [comment]
Same case here. Unable to install .
