### ISSUE TITLE
it's dosen't work on node v4.2.1

### ISSUE THREAD

**Issue by iyjian** [quartzjer/ursa#118]
when i run npm test on node 4.2.1
it gives the following errors:
```
Error: Module did not self-register.
    at Error (native)
    at Object.Module._extensions..node (module.js:460:18)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at bindings (/home/wucho/projects/RTAWeb/node_modules/ursa/node_modules/bindings/bindings.js:76:44)
    at Object.<anonymous> (/home/wucho/projects/RTAWeb/node_modules/ursa/lib/ursa.js:18:37)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
npm ERR! Test failed.  See above for more details.
wucho@wucho-ThinkPad-X1-Carbon-3rd:~/projects/RTAWeb/node_modules/ursa$ node -v
v4.2.1
```

**Comment by sungwoncho** [comment]
I am running node 0.10.35 on ubuntu server, and I have the same error. On my mac, running the same version of node, I don't have this error. I tried `npm rebuild`, and also tried deleting `node_modules` directory and runnign` npm install` again.

Any suggestions?

**Comment by sunsnow8** [comment]
gyp ERR! node -v v4.2.6
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 
npm ERR! Linux 3.10.1-grsec
npm ERR! argv "/home/bae/bae/node-v4.2.6-linux-x64/bin/node" "/home/bae/bae/node-v4.2.6-linux-x64/bin/npm" "install" "--production"
npm ERR! node v4.2.6
npm ERR! npm v2.14.12
npm ERR! code ELIFECYCLE
npm ERR! ursa@0.8.5 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ursa@0.8.5 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the ursa package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR! node-gyp rebuild
npm ERR! You can get their info via:
npm ERR! npm owner ls ursa
npm ERR! There is likely additional logging output above.
npm ERR! Please include the following file with any support request:

**Comment by sunsnow8** [comment]
gyp ERR! node -v v4.2.6
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 
npm ERR! Linux 3.10.1-grsec
npm ERR! argv "/home/bae/bae/node-v4.2.6-linux-x64/bin/node" "/home/bae/bae/node-v4.2.6-linux-x64/bin/npm" "install" "--production"
npm ERR! node v4.2.6
npm ERR! npm v2.14.12
npm ERR! code ELIFECYCLE
npm ERR! ursa@0.9.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ursa@0.9.3 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the ursa package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR! node-gyp rebuild
npm ERR! You can get their info via:
npm ERR! npm owner ls ursa
npm ERR! There is likely additional logging output above.
npm ERR! Please include the following file with any support request:
