### ISSUE TITLE
i dont build this package

### ISSUE THREAD

**Issue by lastuniverse** [quartzjer/ursa#119]
> npm install      
|
> ursa@0.9.1 install /home/roman/games/ursa-master
> node-gyp rebuild

gyp: /usr/lib/node_modules/npm/node_modules/node-gyp/addon-rpm.gypi not found (cwd: /home/roman/games/ursa-master) while reading includes of binding.gyp while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:358:16)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 3.16.7-7-desktop
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/roman/games/ursa-master
gyp ERR! node -v v4.2.1
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 

npm ERR! Linux 3.16.7-7-desktop
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! node v4.2.1
npm ERR! npm  v2.14.7
npm ERR! code ELIFECYCLE
npm ERR! ursa@0.9.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ursa@0.9.1 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the ursa package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls ursa
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     [/home/roman/games/ursa-master/npm-debug.log](http://pastebin.com/VjQTzZaB)

**Comment by Splaktar** [comment]
Same issue on OS X with npm v3.5.2 and node v4.2.2.

**Comment by quartzjer** [comment]
I'm looking for a new maintainer: https://github.com/quartzjer/ursa#maintainer-needed

**Comment by davedoesdev** [comment]
@lastuniverse although I don't use SUSE, I believe this might have been caused by https://bugzilla.opensuse.org/show_bug.cgi?id=948045

**Comment by murphman300** [comment]
Fixed this on AWS ubuntu LTS 16.4 by installing python... Seems like this package has a python dependency.

ubuntu: `sudo apt-get install python` did it for me
