### ISSUE TITLE
Makefile:1: /env.mak: No such file or directory

### ISSUE THREAD

**Issue by schwiet** [quartzjer/ursa#125]
I'm trying to run a node application on my Synology box that depends on ursa. Installing the dependencies with `npm install` fails while trying to `gyp build` ursa; the output is paste below. I know very little about make, does this error mean something to someone? The first line of the Makefile in `node_modules/ursa/build/` includes `/env.mak`.

Thanks

    > ursa@0.9.1 install /home/proj/node_modules/ursa
    > node-gyp rebuild

    make: Entering directory `/home/proj/node_modules/ursa/build'
    Makefile:1: /env.mak: No such file or directory
    make: *** No rule to make target `/env.mak'.  Stop.
    make: Leaving directory `/home/proj/node_modules/ursa/build'
    gyp ERR! build error 
    gyp ERR! stack Error: `make` failed with exit code: 2
    gyp ERR! stack     at ChildProcess.onExit (/volume1/@appstore/Node.js/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
    gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
    gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
    gyp ERR! System Linux 3.2.40
    gyp ERR! command "node"  "/volume1/@appstore/Node.js/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
    gyp ERR! cwd /home/proj/node_modules/ursa
    gyp ERR! node -v v0.12.4
    gyp ERR! node-gyp -v v1.0.3
    gyp ERR! not ok 

    npm ERR! Linux 3.2.40
    npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install"
    npm ERR! node v0.12.4
    npm ERR! npm  v2.10.1
    npm ERR! code ELIFECYCLE
    npm ERR! ursa@0.9.1 install: `node-gyp rebuild`
    npm ERR! Exit status 1
    npm ERR! 
    npm ERR! Failed at the ursa@0.9.1 install script 'node-gyp rebuild'.
    npm ERR! This is most likely a problem with the ursa package,
    npm ERR! not with npm itself.
    npm ERR! Tell the author that this fails on your system:
    npm ERR!     node-gyp rebuild
    npm ERR! You can get their info via:
    npm ERR!     npm owner ls ursa
    npm ERR! There is likely additional logging output above.

**Comment by schwiet** [comment]
I installed Debian on the Synology and and was successful at building it inside that environment. Not sure exactly what was wrong in DSM...
