### ISSUE TITLE
Error require'ing ursa. Error: Module version mismatch. Expected 48, got 47.

### ISSUE THREAD

**Issue by cmalcom** [quartzjer/ursa#136]
I was able to get 0.9.3 installed with Node 6.0.0.
Running on OSX (10.11.4)

When I add require('ursa') and run the project it throws with :

....../node_modules/bindings/bindings.js:83
        throw e
        ^

Error: Module version mismatch. Expected 48, got 47.
    at Error (native)
    at Object.Module._extensions..node (module.js:568:18)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)
    at bindings (/Users/xxxxx/Documents/MyProjects/projectName/bc-ui/node_modules/bindings/bindings.js:76:44)
    at Object.<anonymous> (/Users/xxxxx/Documents/MyProjects/projectName/bc-ui/node_modules/ursa/lib/ursa.js:18:37)
    at Module._compile (module.js:541:32)

**Comment by quartzjer** [comment]
new v0.9.4 version is published, re-open if that doesn't fix this, thx!

**Comment by dventurino** [comment]
Same error on macOS 10.12.1 and Node v7.1.0 (but also 6.9.1):

App threw an error during load
Error: Module version mismatch. Expected 50, got 51.
    at Error (native)
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:178:20)
    at Object.Module._extensions..node (module.js:583:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:178:20)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at bindings (/Users/xxxx/git/ShareBox/node_modules/bindings/bindings.js:76:44)
