### ISSUE TITLE
Error: `gyp` failed with exit code: 1

### ISSUE THREAD

**Issue by WindBlades** [quartzjer/ursa#157]
I installed everything that was needed as well as trying the solutions but nothing works I remain constantly with this error:

gyp ERR! stack     at Process.ChildProcess._handle.onexit (inter
s.js:215:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\User
pData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\
" "rebuild"
gyp ERR! cwd C:\Windows\system32\node_modules\ursa
gyp ERR! node -v v6.10.2
gyp ERR! node-gyp -v v3.6.0
gyp ERR! not ok
npm WARN discord.js@10.0.1 requires a peer of node-opus@^0.2.1 b
alled.
npm WARN bottest@1.0.0 No repository field.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ursa@0.9.4 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ursa@0.9.4 install script 'node-gyp rebui
npm ERR! Make sure you have the latest version of node.js and np
npm ERR! If you do, this is most likely a problem with the ursa
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for thi
npm ERR!     npm bugs ursa
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls ursa
npm ERR! There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\WindBlade\AppData\Roaming\npm-cache\_logs\
_56_885Z-debug.log

C:\Windows\system32>

------
Environment: Windows 7
Version of node: 6.10.2
Version of npm: 4.50

**Comment by WindBlades** [comment]
logs:
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\WindBlade\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'ursa' ]
2 info using npm@4.5.0
3 info using node@v6.10.2
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly fetchPackageMetaData ursa
8 silly fetchNamedPackageData ursa
9 silly mapToRegistry name ursa
10 silly mapToRegistry using default registry
11 silly mapToRegistry registry https://registry.npmjs.org/
12 silly mapToRegistry data Result {
12 silly mapToRegistry   raw: 'ursa',
12 silly mapToRegistry   scope: null,
12 silly mapToRegistry   escapedName: 'ursa',
12 silly mapToRegistry   name: 'ursa',
12 silly mapToRegistry   rawSpec: '',
12 silly mapToRegistry   spec: 'latest',
12 silly mapToRegistry   type: 'tag' }
13 silly mapToRegistry uri https://registry.npmjs.org/ursa
14 verbose request uri https://registry.npmjs.org/ursa
15 verbose request no auth needed
16 info attempt registry request try #1 at 15:12:55
17 verbose request id fd498666b580827a
18 verbose etag W/"58a3e42f-d417"
19 verbose lastModified Wed, 15 Feb 2017 05:16:31 GMT
20 http request GET https://registry.npmjs.org/ursa
21 http 304 https://registry.npmjs.org/ursa
22 verbose headers { date: 'Wed, 26 Apr 2017 13:12:54 GMT',
22 verbose headers   via: '1.1 varnish',
22 verbose headers   'cache-control': 'max-age=300',
22 verbose headers   etag: 'W/"58a3e42f-d417"',
22 verbose headers   age: '122',
22 verbose headers   connection: 'keep-alive',
22 verbose headers   'x-served-by': 'cache-cdg8729-CDG',
22 verbose headers   'x-cache': 'HIT',
22 verbose headers   'x-cache-hits': '1',
22 verbose headers   'x-timer': 'S1493212374.414650,VS0,VE1',
22 verbose headers   vary: 'Accept-Encoding' }
23 silly get cb [ 304,
23 silly get   { date: 'Wed, 26 Apr 2017 13:12:54 GMT',
23 silly get     via: '1.1 varnish',
23 silly get     'cache-control': 'max-age=300',
23 silly get     etag: 'W/"58a3e42f-d417"',
23 silly get     age: '122',
23 silly get     connection: 'keep-alive',
23 silly get     'x-served-by': 'cache-cdg8729-CDG',
23 silly get     'x-cache': 'HIT',
23 silly get     'x-cache-hits': '1',
23 silly get     'x-timer': 'S1493212374.414650,VS0,VE1',
23 silly get     vary: 'Accept-Encoding' } ]
24 verbose etag https://registry.npmjs.org/ursa from cache
25 verbose get saving ursa to C:\Users\WindBlade\AppData\Roaming\npm-cache\registry.npmjs.org\ursa\.cache.json
26 verbose correctMkdir C:\Users\WindBlade\AppData\Roaming\npm-cache correctMkdir not in flight; initializing
27 silly install normalizeTree
28 silly loadCurrentTree Finishing
29 silly loadIdealTree Starting
30 silly install loadIdealTree
31 silly cloneCurrentTree Starting
32 silly install cloneCurrentTreeToIdealTree
33 silly cloneCurrentTree Finishing
34 silly loadShrinkwrap Starting
35 silly install loadShrinkwrap
36 silly loadShrinkwrap Finishing
37 silly loadAllDepsIntoIdealTree Starting
38 silly install loadAllDepsIntoIdealTree
39 silly resolveWithNewModule ursa@0.9.4 checking installable status
40 silly cache add args [ 'ursa', null ]
41 verbose cache add spec ursa
42 silly cache add parsed spec Result {
42 silly cache add   raw: 'ursa',
42 silly cache add   scope: null,
42 silly cache add   escapedName: 'ursa',
42 silly cache add   name: 'ursa',
42 silly cache add   rawSpec: '',
42 silly cache add   spec: 'latest',
42 silly cache add   type: 'tag' }
43 silly addNamed ursa@latest
44 verbose addNamed "latest" is being treated as a dist-tag for ursa
45 info addNameTag [ 'ursa', 'latest' ]
46 silly mapToRegistry name ursa
47 silly mapToRegistry using default registry
48 silly mapToRegistry registry https://registry.npmjs.org/
49 silly mapToRegistry data Result {
49 silly mapToRegistry   raw: 'ursa',
49 silly mapToRegistry   scope: null,
49 silly mapToRegistry   escapedName: 'ursa',
49 silly mapToRegistry   name: 'ursa',
49 silly mapToRegistry   rawSpec: '',
49 silly mapToRegistry   spec: 'latest',
49 silly mapToRegistry   type: 'tag' }
50 silly mapToRegistry uri https://registry.npmjs.org/ursa
51 verbose addNameTag registry:https://registry.npmjs.org/ursa not in flight; fetching
52 verbose get https://registry.npmjs.org/ursa not expired, no request
53 silly addNameTag next cb for ursa with tag latest
54 silly addNamed ursa@0.9.4
55 verbose addNamed "0.9.4" is a plain semver version for ursa
56 silly cache afterAdd ursa@0.9.4
57 verbose afterAdd C:\Users\WindBlade\AppData\Roaming\npm-cache\ursa\0.9.4\package\package.json not in flight; writing
58 verbose correctMkdir C:\Users\WindBlade\AppData\Roaming\npm-cache correctMkdir not in flight; initializing
59 verbose afterAdd C:\Users\WindBlade\AppData\Roaming\npm-cache\ursa\0.9.4\package\package.json written
60 silly loadAllDepsIntoIdealTree Finishing
61 silly loadIdealTree Finishing
62 silly currentTree bottest@1.0.0
62 silly currentTree +-- ajv@4.11.7
62 silly currentTree +-- ansi-regex@2.1.1
62 silly currentTree +-- ansi-styles@2.2.1
62 silly currentTree +-- asn1@0.2.3
62 silly currentTree +-- assert-plus@0.2.0
62 silly currentTree +-- async@1.5.2
62 silly currentTree +-- asynckit@0.4.0
62 silly currentTree +-- aws-sign2@0.6.0
62 silly currentTree +-- aws4@1.6.0
62 silly currentTree +-- bcrypt-pbkdf@1.0.1
62 silly currentTree +-- bindings@1.2.1
62 silly currentTree +-- boom@2.10.1
62 silly currentTree +-- buffer-equal@1.0.0
62 silly currentTree +-- buffer-shims@1.0.0
62 silly currentTree +-- caseless@0.11.0
62 silly currentTree +-- chalk@1.1.3
62 silly currentTree +-- co@4.6.0
62 silly currentTree +-- combined-stream@1.0.5
62 silly currentTree +-- commander@2.9.0
62 silly currentTree +-- component-emitter@1.2.1
62 silly currentTree +-- cookiejar@2.1.0
62 silly currentTree +-- core-util-is@1.0.2
62 silly currentTree +-- cryptiles@2.0.5
62 silly currentTree +-- dashdash@1.14.1
62 silly currentTree | `-- assert-plus@1.0.0
62 silly currentTree +-- debug@2.4.4
62 silly currentTree +-- delayed-stream@1.0.0
62 silly currentTree +-- discord.js@10.0.1
62 silly currentTree +-- ecc-jsbn@0.1.1
62 silly currentTree +-- endian-toggle@0.0.0
62 silly currentTree +-- escape-string-regexp@1.0.5
62 silly currentTree +-- extend@3.0.0
62 silly currentTree +-- extsprintf@1.0.2
62 silly currentTree +-- forever-agent@0.6.1
62 silly currentTree +-- form-data@1.0.0-rc4
62 silly currentTree +-- formidable@1.0.17
62 silly currentTree +-- generate-function@2.0.0
62 silly currentTree +-- generate-object-property@1.2.0
62 silly currentTree +-- getpass@0.1.7
62 silly currentTree | `-- assert-plus@1.0.0
62 silly currentTree +-- graceful-readlink@1.0.1
62 silly currentTree +-- har-validator@2.0.6
62 silly currentTree +-- has-ansi@2.0.0
62 silly currentTree +-- hawk@3.1.3
62 silly currentTree +-- hoek@2.16.3
62 silly currentTree +-- http-signature@1.1.1
62 silly currentTree +-- inherits@2.0.3
62 silly currentTree +-- is-my-json-valid@2.16.0
62 silly currentTree +-- is-property@1.0.2
62 silly currentTree +-- is-typedarray@1.0.0
62 silly currentTree +-- isarray@1.0.0
62 silly currentTree +-- isstream@0.1.2
62 silly currentTree +-- jodid25519@1.0.2
62 silly currentTree +-- jsbn@0.1.1
62 silly currentTree +-- json-schema@0.2.3
62 silly currentTree +-- json-stable-stringify@1.0.1
62 silly currentTree +-- json-stringify-safe@5.0.1
62 silly currentTree +-- jsonify@0.0.0
62 silly currentTree +-- jsonpointer@4.0.1
62 silly currentTree +-- jsprim@1.4.0
62 silly currentTree | `-- assert-plus@1.0.0
62 silly currentTree +-- lodash.get@4.4.2
62 silly currentTree +-- lodash.merge@4.6.0
62 silly currentTree +-- lodash.reduce@4.6.0
62 silly currentTree +-- lodash@3.3.0
62 silly currentTree +-- macaddress@0.2.8
62 silly currentTree +-- methods@1.1.2
62 silly currentTree +-- mime-db@1.25.0
62 silly currentTree +-- mime-types@2.1.13
62 silly currentTree +-- mime@1.3.4
62 silly currentTree +-- minecraft-data@2.14.0
62 silly currentTree +-- minecraft-protocol@1.1.3
62 silly currentTree +-- mineflayer@2.1.1
62 silly currentTree +-- mojangson@0.2.3
62 silly currentTree +-- ms@0.7.2
62 silly currentTree +-- nan@2.4.0
62 silly currentTree +-- node-rsa@0.2.30
62 silly currentTree +-- node-uuid@1.4.8
62 silly currentTree +-- oauth-sign@0.8.2
62 silly currentTree +-- options@0.0.6
62 silly currentTree +-- opusscript@0.0.1
62 silly currentTree +-- pinkie-promise@2.0.1
62 silly currentTree +-- pinkie@2.0.4
62 silly currentTree +-- prismarine-biome@1.0.1
62 silly currentTree +-- prismarine-block@1.0.1
62 silly currentTree +-- prismarine-chunk@1.5.1
62 silly currentTree +-- prismarine-entity@0.2.0
62 silly currentTree +-- prismarine-item@1.0.2
62 silly currentTree +-- prismarine-nbt@1.1.0
62 silly currentTree +-- prismarine-recipe@1.0.1
62 silly currentTree +-- prismarine-windows@1.1.0
62 silly currentTree +-- process-nextick-args@1.0.7
62 silly currentTree +-- protodef-validator@1.1.7
62 silly currentTree +-- protodef@1.5.1
62 silly currentTree +-- punycode@1.4.1
62 silly currentTree +-- qs@6.3.0
62 silly currentTree +-- readable-stream@2.2.2
62 silly currentTree +-- request@2.78.0
62 silly currentTree | `-- form-data@2.1.4
62 silly currentTree +-- sntp@1.0.9
62 silly currentTree +-- sshpk@1.13.0
62 silly currentTree | `-- assert-plus@1.0.0
62 silly currentTree +-- string_decoder@0.10.31
62 silly currentTree +-- stringstream@0.0.5
62 silly currentTree +-- strip-ansi@3.0.1
62 silly currentTree +-- superagent@2.3.0
62 silly currentTree +-- supports-color@2.0.0
62 silly currentTree +-- tough-cookie@2.3.2
62 silly currentTree +-- tunnel-agent@0.4.3
62 silly currentTree +-- tweetnacl@0.14.5
62 silly currentTree +-- uint4@0.1.2
62 silly currentTree +-- ultron@1.0.2
62 silly currentTree +-- ursa-purejs@0.0.3
62 silly currentTree +-- util-deprecate@1.0.2
62 silly currentTree +-- uuid-1345@0.99.6
62 silly currentTree +-- uuid@2.0.3
62 silly currentTree +-- vec3@0.1.3
62 silly currentTree +-- verror@1.3.6
62 silly currentTree +-- ws@1.1.1
62 silly currentTree +-- xtend@4.0.1
62 silly currentTree `-- yggdrasil@0.2.0
63 silly idealTree bottest@1.0.0
63 silly idealTree +-- ajv@4.11.7
63 silly idealTree +-- ansi-regex@2.1.1
63 silly idealTree +-- ansi-styles@2.2.1
63 silly idealTree +-- asn1@0.2.3
63 silly idealTree +-- assert-plus@0.2.0
63 silly idealTree +-- async@1.5.2
63 silly idealTree +-- asynckit@0.4.0
63 silly idealTree +-- aws-sign2@0.6.0
63 silly idealTree +-- aws4@1.6.0
63 silly idealTree +-- bcrypt-pbkdf@1.0.1
63 silly idealTree +-- bindings@1.2.1
63 silly idealTree +-- boom@2.10.1
63 silly idealTree +-- buffer-equal@1.0.0
63 silly idealTree +-- buffer-shims@1.0.0
63 silly idealTree +-- caseless@0.11.0
63 silly idealTree +-- chalk@1.1.3
63 silly idealTree +-- co@4.6.0
63 silly idealTree +-- combined-stream@1.0.5
63 silly idealTree +-- commander@2.9.0
63 silly idealTree +-- component-emitter@1.2.1
63 silly idealTree +-- cookiejar@2.1.0
63 silly idealTree +-- core-util-is@1.0.2
63 silly idealTree +-- cryptiles@2.0.5
63 silly idealTree +-- dashdash@1.14.1
63 silly idealTree | `-- assert-plus@1.0.0
63 silly idealTree +-- debug@2.4.4
63 silly idealTree +-- delayed-stream@1.0.0
63 silly idealTree +-- discord.js@10.0.1
63 silly idealTree +-- ecc-jsbn@0.1.1
63 silly idealTree +-- endian-toggle@0.0.0
63 silly idealTree +-- escape-string-regexp@1.0.5
63 silly idealTree +-- extend@3.0.0
63 silly idealTree +-- extsprintf@1.0.2
63 silly idealTree +-- forever-agent@0.6.1
63 silly idealTree +-- form-data@1.0.0-rc4
63 silly idealTree +-- formidable@1.0.17
63 silly idealTree +-- generate-function@2.0.0
63 silly idealTree +-- generate-object-property@1.2.0
63 silly idealTree +-- getpass@0.1.7
63 silly idealTree | `-- assert-plus@1.0.0
63 silly idealTree +-- graceful-readlink@1.0.1
63 silly idealTree +-- har-validator@2.0.6
63 silly idealTree +-- has-ansi@2.0.0
63 silly idealTree +-- hawk@3.1.3
63 silly idealTree +-- hoek@2.16.3
63 silly idealTree +-- http-signature@1.1.1
63 silly idealTree +-- inherits@2.0.3
63 silly idealTree +-- is-my-json-valid@2.16.0
63 silly idealTree +-- is-property@1.0.2
63 silly idealTree +-- is-typedarray@1.0.0
63 silly idealTree +-- isarray@1.0.0
63 silly idealTree +-- isstream@0.1.2
63 silly idealTree +-- jodid25519@1.0.2
63 silly idealTree +-- jsbn@0.1.1
63 silly idealTree +-- json-schema@0.2.3
63 silly idealTree +-- json-stable-stringify@1.0.1
63 silly idealTree +-- json-stringify-safe@5.0.1
63 silly idealTree +-- jsonify@0.0.0
63 silly idealTree +-- jsonpointer@4.0.1
63 silly idealTree +-- jsprim@1.4.0
63 silly idealTree | `-- assert-plus@1.0.0
63 silly idealTree +-- lodash.get@4.4.2
63 silly idealTree +-- lodash.merge@4.6.0
63 silly idealTree +-- lodash.reduce@4.6.0
63 silly idealTree +-- lodash@3.3.0
63 silly idealTree +-- macaddress@0.2.8
63 silly idealTree +-- methods@1.1.2
63 silly idealTree +-- mime-db@1.25.0
63 silly idealTree +-- mime-types@2.1.13
63 silly idealTree +-- mime@1.3.4
63 silly idealTree +-- minecraft-data@2.14.0
63 silly idealTree +-- minecraft-protocol@1.1.3
63 silly idealTree +-- mineflayer@2.1.1
63 silly idealTree +-- mojangson@0.2.3
63 silly idealTree +-- ms@0.7.2
63 silly idealTree +-- nan@2.4.0
63 silly idealTree +-- node-rsa@0.2.30
63 silly idealTree +-- node-uuid@1.4.8
63 silly idealTree +-- oauth-sign@0.8.2
63 silly idealTree +-- options@0.0.6
63 silly idealTree +-- opusscript@0.0.1
63 silly idealTree +-- pinkie-promise@2.0.1
63 silly idealTree +-- pinkie@2.0.4
63 silly idealTree +-- prismarine-biome@1.0.1
63 silly idealTree +-- prismarine-block@1.0.1
63 silly idealTree +-- prismarine-chunk@1.5.1
63 silly idealTree +-- prismarine-entity@0.2.0
63 silly idealTree +-- prismarine-item@1.0.2
63 silly idealTree +-- prismarine-nbt@1.1.0
63 silly idealTree +-- prismarine-recipe@1.0.1
63 silly idealTree +-- prismarine-windows@1.1.0
63 silly idealTree +-- process-nextick-args@1.0.7
63 silly idealTree +-- protodef-validator@1.1.7
63 silly idealTree +-- protodef@1.5.1
63 silly idealTree +-- punycode@1.4.1
63 silly idealTree +-- qs@6.3.0
63 silly idealTree +-- readable-stream@2.2.2
63 silly idealTree +-- request@2.78.0
63 silly idealTree | `-- form-data@2.1.4
63 silly idealTree +-- sntp@1.0.9
63 silly idealTree +-- sshpk@1.13.0
63 silly idealTree | `-- assert-plus@1.0.0
63 silly idealTree +-- string_decoder@0.10.31
63 silly idealTree +-- stringstream@0.0.5
63 silly idealTree +-- strip-ansi@3.0.1
63 silly idealTree +-- superagent@2.3.0
63 silly idealTree +-- supports-color@2.0.0
63 silly idealTree +-- tough-cookie@2.3.2
63 silly idealTree +-- tunnel-agent@0.4.3
63 silly idealTree +-- tweetnacl@0.14.5
63 silly idealTree +-- uint4@0.1.2
63 silly idealTree +-- ultron@1.0.2
63 silly idealTree +-- ursa-purejs@0.0.3
63 silly idealTree +-- ursa@0.9.4
63 silly idealTree +-- util-deprecate@1.0.2
63 silly idealTree +-- uuid-1345@0.99.6
63 silly idealTree +-- uuid@2.0.3
63 silly idealTree +-- vec3@0.1.3
63 silly idealTree +-- verror@1.3.6
63 silly idealTree +-- ws@1.1.1
63 silly idealTree +-- xtend@4.0.1
63 silly idealTree `-- yggdrasil@0.2.0
64 silly generateActionsToTake Starting
65 silly install generateActionsToTake
66 silly generateActionsToTake Finishing
67 silly diffTrees action count 1
68 silly diffTrees add ursa@0.9.4
69 silly decomposeActions action count 8
70 silly decomposeActions fetch ursa@0.9.4
71 silly decomposeActions extract ursa@0.9.4
72 silly decomposeActions test ursa@0.9.4
73 silly decomposeActions preinstall ursa@0.9.4
74 silly decomposeActions build ursa@0.9.4
75 silly decomposeActions install ursa@0.9.4
76 silly decomposeActions postinstall ursa@0.9.4
77 silly decomposeActions finalize ursa@0.9.4
78 silly runTopLevelLifecycles Starting
79 silly executeActions Starting
80 silly install executeActions
81 silly doSerial global-install 0
82 silly doParallel fetch 1
83 verbose correctMkdir C:\Users\WindBlade\AppData\Roaming\npm-cache\_locks correctMkdir not in flight; initializing
84 verbose lock using C:\Users\WindBlade\AppData\Roaming\npm-cache\_locks\staging-ecddf487eb87445c.lock for C:\Windows\system32\node_modules\.staging
85 silly doParallel extract 1
86 silly extract ursa@0.9.4
87 verbose unbuild node_modules\.staging\ursa-15f410fe
88 silly gentlyRm C:\Windows\system32\node_modules\.staging\ursa-15f410fe is being purged from base C:\Windows\system32
89 verbose gentlyRm don't care about contents; nuking C:\Windows\system32\node_modules\.staging\ursa-15f410fe
90 verbose tar unpack C:\Users\WindBlade\AppData\Roaming\npm-cache\ursa\0.9.4\package.tgz
91 verbose tar unpacking to C:\Windows\system32\node_modules\.staging\ursa-15f410fe
92 silly gentlyRm C:\Windows\system32\node_modules\.staging\ursa-15f410fe is being purged
93 verbose gentlyRm don't care about contents; nuking C:\Windows\system32\node_modules\.staging\ursa-15f410fe
94 silly gunzTarPerm modes [ '777', '666' ]
95 silly gunzTarPerm extractEntry package.json
96 silly gunzTarPerm modified mode [ 'package.json', 420, 438 ]
97 silly gunzTarPerm extractEntry .npmignore
98 silly gunzTarPerm modified mode [ '.npmignore', 420, 438 ]
99 silly gunzTarPerm extractEntry README.md
100 silly gunzTarPerm modified mode [ 'README.md', 420, 438 ]
101 silly gunzTarPerm extractEntry binding.gyp
102 silly gunzTarPerm modified mode [ 'binding.gyp', 420, 438 ]
103 silly gunzTarPerm extractEntry .travis.yml
104 silly gunzTarPerm modified mode [ '.travis.yml', 420, 438 ]
105 silly gunzTarPerm extractEntry lib/ursa.js
106 silly gunzTarPerm modified mode [ 'lib/ursa.js', 420, 438 ]
107 silly gunzTarPerm extractEntry src/ursaNative.cc
108 silly gunzTarPerm modified mode [ 'src/ursaNative.cc', 420, 438 ]
109 silly gunzTarPerm extractEntry src/ursaNative.h
110 silly gunzTarPerm modified mode [ 'src/ursaNative.h', 420, 438 ]
111 silly gunzTarPerm extractEntry LICENSE.txt
112 silly gunzTarPerm modified mode [ 'LICENSE.txt', 420, 438 ]
113 silly gunzTarPerm extractEntry test/fixture.js
114 silly gunzTarPerm modified mode [ 'test/fixture.js', 420, 438 ]
115 silly gunzTarPerm extractEntry test/native.js
116 silly gunzTarPerm modified mode [ 'test/native.js', 420, 438 ]
117 silly gunzTarPerm extractEntry test/test.js
118 silly gunzTarPerm modified mode [ 'test/test.js', 420, 438 ]
119 silly gunzTarPerm extractEntry test/blort.pub
120 silly gunzTarPerm modified mode [ 'test/blort.pub', 420, 438 ]
121 silly gunzTarPerm extractEntry test/blort.sshpub
122 silly gunzTarPerm modified mode [ 'test/blort.sshpub', 420, 438 ]
123 silly gunzTarPerm extractEntry test/blort-pass.pem
124 silly gunzTarPerm modified mode [ 'test/blort-pass.pem', 420, 438 ]
125 silly gunzTarPerm extractEntry test/another_zorch.pem
126 silly gunzTarPerm modified mode [ 'test/another_zorch.pem', 420, 438 ]
127 silly gunzTarPerm extractEntry test/pss_tv.pub
128 silly gunzTarPerm modified mode [ 'test/pss_tv.pub', 420, 438 ]
129 silly gunzTarPerm extractEntry test/blort.pem
130 silly gunzTarPerm modified mode [ 'test/blort.pem', 420, 438 ]
131 silly gunzTarPerm extractEntry test/zorch.pem
132 silly gunzTarPerm modified mode [ 'test/zorch.pem', 420, 438 ]
133 silly gunzTarPerm extractEntry test/zorch.pub
134 silly gunzTarPerm modified mode [ 'test/zorch.pub', 420, 438 ]
135 silly gentlyRm C:\Windows\system32\node_modules\.staging\ursa-15f410fe\node_modules is being purged
136 verbose gentlyRm don't care about contents; nuking C:\Windows\system32\node_modules\.staging\ursa-15f410fe\node_modules
137 silly doParallel preinstall 1
138 silly preinstall ursa@0.9.4
139 info lifecycle ursa@0.9.4~preinstall: ursa@0.9.4
140 silly lifecycle ursa@0.9.4~preinstall: no script for preinstall, continuing
141 silly doReverseSerial remove 0
142 silly doSerial move 0
143 silly doSerial finalize 1
144 silly finalize C:\Windows\system32\node_modules\ursa
145 silly doSerial build 1
146 silly build ursa@0.9.4
147 info linkStuff ursa@0.9.4
148 silly linkStuff ursa@0.9.4 has C:\Windows\system32\node_modules as its parent node_modules
149 verbose linkBins ursa@0.9.4
150 verbose linkMans ursa@0.9.4
151 silly doSerial global-link 0
152 silly doParallel update-linked 0
153 silly doSerial install 1
154 silly install ursa@0.9.4
155 info lifecycle ursa@0.9.4~install: ursa@0.9.4
156 verbose lifecycle ursa@0.9.4~install: unsafe-perm in lifecycle true
157 verbose lifecycle ursa@0.9.4~install: PATH: C:\Users\WindBlade\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin;C:\Windows\system32\node_modules\ursa\node_modules\.bin;C:\Windows\system32\node_modules\.bin;C:\Program Files\Common Files\Microsoft Shared\Windows Live;C:\Program Files (x86)\Common Files\Microsoft Shared\Windows Live;C:\ProgramData\Oracle\Java\javapath;C:\Program Files\Java\jdk1.8.0_101\bin;C:\Program Files (x86)\Windows Live\Shared;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\ffmpeg\bin;C:\Program Files (x86)\Bitvise SSH Client;C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit\;C:\Program Files (x86)\Skype\Phone\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Users\WindBlade\AppData\Roaming\npm;C:\Program Files\nodejs\;C:\Program Files\Microsoft Windows Performance Toolkit\;C:\Program Files\Microsoft SQL Server\110\Tools\Binn\;C:\Program Files (x86)\Microsoft SDKs\TypeScript\1.0\;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\Windows/system32/WindowsPowerShell/v1.0
158 verbose lifecycle ursa@0.9.4~install: CWD: C:\Windows\system32\node_modules\ursa
159 silly lifecycle ursa@0.9.4~install: Args: [ '/d /s /c', 'node-gyp rebuild' ]
160 silly lifecycle ursa@0.9.4~install: Returned: code: 1  signal: null
161 info lifecycle ursa@0.9.4~install: Failed to exec install script
162 verbose unlock done using C:\Users\WindBlade\AppData\Roaming\npm-cache\_locks\staging-ecddf487eb87445c.lock for C:\Windows\system32\node_modules\.staging
163 silly rollbackFailedOptional Starting
164 silly gentlyRm C:\Windows\system32\node_modules\ursa is being purged from base C:\Windows\system32
165 verbose gentlyRm don't care about contents; nuking C:\Windows\system32\node_modules\ursa
166 silly gentlyRm C:\Windows\system32\node_modules\ursa is being purged from base C:\Windows\system32
167 verbose gentlyRm don't care about contents; nuking C:\Windows\system32\node_modules\ursa
168 silly gentlyRm C:\Windows\system32\node_modules\ursa is being purged from base C:\Windows\system32
169 verbose gentlyRm don't care about contents; nuking C:\Windows\system32\node_modules\ursa
170 silly gentlyRm C:\Windows\system32\node_modules\ursa is being purged from base C:\Windows\system32
171 verbose gentlyRm don't care about contents; nuking C:\Windows\system32\node_modules\ursa
172 silly gentlyRm C:\Windows\system32\node_modules\ursa is being purged from base C:\Windows\system32
173 verbose gentlyRm don't care about contents; nuking C:\Windows\system32\node_modules\ursa
174 silly gentlyRm C:\Windows\system32\node_modules\ursa is being purged from base C:\Windows\system32
175 verbose gentlyRm don't care about contents; nuking C:\Windows\system32\node_modules\ursa
176 silly gentlyRm C:\Windows\system32\node_modules\ursa is being purged from base C:\Windows\system32
177 verbose gentlyRm don't care about contents; nuking C:\Windows\system32\node_modules\ursa
178 silly gentlyRm C:\Windows\system32\node_modules\ursa is being purged from base C:\Windows\system32
179 verbose gentlyRm don't care about contents; nuking C:\Windows\system32\node_modules\ursa
180 silly vacuum-fs purging C:\Windows\system32\node_modules\ursa
181 silly vacuum-fs purging C:\Windows\system32\node_modules\ursa
182 silly vacuum-fs purging C:\Windows\system32\node_modules\ursa
183 silly vacuum-fs purging C:\Windows\system32\node_modules\ursa
184 silly vacuum-fs purging C:\Windows\system32\node_modules\ursa
185 silly vacuum-fs purging C:\Windows\system32\node_modules\ursa
186 silly vacuum-fs purging C:\Windows\system32\node_modules\ursa
187 silly vacuum-fs purging C:\Windows\system32\node_modules\ursa
188 silly vacuum-fs quitting because other entries in C:\Windows\system32\node_modules
189 silly vacuum-fs quitting because other entries in C:\Windows\system32\node_modules
190 silly vacuum-fs quitting because other entries in C:\Windows\system32\node_modules
191 silly vacuum-fs quitting because other entries in C:\Windows\system32\node_modules
192 silly vacuum-fs quitting because other entries in C:\Windows\system32\node_modules
193 silly vacuum-fs quitting because other entries in C:\Windows\system32\node_modules
194 silly vacuum-fs quitting because other entries in C:\Windows\system32\node_modules
195 silly vacuum-fs quitting because other entries in C:\Windows\system32\node_modules
196 silly rollbackFailedOptional Finishing
197 silly runTopLevelLifecycles Finishing
198 silly install printInstalled
199 warn discord.js@10.0.1 requires a peer of node-opus@^0.2.1 but none was installed.
200 warn bottest@1.0.0 No repository field.
201 verbose stack Error: ursa@0.9.4 install: `node-gyp rebuild`
201 verbose stack Exit status 1
201 verbose stack     at EventEmitter.<anonymous> (C:\Users\WindBlade\AppData\Roaming\npm\node_modules\npm\lib\utils\lifecycle.js:279:16)
201 verbose stack     at emitTwo (events.js:106:13)
201 verbose stack     at EventEmitter.emit (events.js:191:7)
201 verbose stack     at ChildProcess.<anonymous> (C:\Users\WindBlade\AppData\Roaming\npm\node_modules\npm\lib\utils\spawn.js:40:14)
201 verbose stack     at emitTwo (events.js:106:13)
201 verbose stack     at ChildProcess.emit (events.js:191:7)
201 verbose stack     at maybeClose (internal/child_process.js:886:16)
201 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
202 verbose pkgid ursa@0.9.4
203 verbose cwd C:\Windows\system32
204 verbose Windows_NT 6.1.7601
205 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\WindBlade\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "ursa"
206 verbose node v6.10.2
207 verbose npm  v4.5.0
208 error code ELIFECYCLE
209 error errno 1
210 error ursa@0.9.4 install: `node-gyp rebuild`
210 error Exit status 1
211 error Failed at the ursa@0.9.4 install script 'node-gyp rebuild'.
211 error Make sure you have the latest version of node.js and npm installed.
211 error If you do, this is most likely a problem with the ursa package,
211 error not with npm itself.
211 error Tell the author that this fails on your system:
211 error     node-gyp rebuild
211 error You can get information on how to open an issue for this project with:
211 error     npm bugs ursa
211 error Or if that isn't available, you can get their info via:
211 error     npm owner ls ursa
211 error There is likely additional logging output above.
212 verbose exit [ 1, true ]
