### ISSUE TITLE
npm install ursa on ubuntu

### ISSUE THREAD

**Issue by MisterBalboa** [quartzjer/ursa#171]
Hello, i am trying to install ursa on ubuntu machine but have a problem. 
- node -v v10.4.1
- node-gyp -v v3.6.2

I cannot figure out the error from the err stack:

gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:237:12)
gyp ERR! System Linux 4.4.0-1060-aws
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/ubuntu/buze-payments/node_modules/ursa
gyp ERR! node -v v10.4.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm WARN ms-payments@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ursa@0.9.4 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ursa@0.9.4 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ubuntu/.npm/_logs/2018-06-14T21_53_02_279Z-debug.log

Any idea where could be the problem?

**Comment by knobik** [comment]
`npm rebuild` as root helped in my case.

**Comment by rzr** [comment]
Please confirm this is reproducible on current master, if not then this bug can be closed once npm package is released.

**Comment by rzr** [comment]
Relate-to: https://github.com/JoshKaufman/ursa/issues/175

**Comment by marclijour** [comment]
Same issue on Ubuntu 19.04
node -v v10.15.2
node-gyp -v v3.8.0

```
$ sudo npm i -g ursa-optional@latest

> ursa-optional@0.10.1 install /usr/local/lib/node_modules/ursa-optional
> node rebuild.js

ursaNative bindings compilation fail. This is not an issue. Modules that depend on it will use fallbacks.
fs.js:115
    throw err;
    ^

Error: EACCES: permission denied, open './stdout.log'
    at Object.openSync (fs.js:439:3)
    at Object.writeFileSync (fs.js:1190:35)
    at Object.<anonymous> (/usr/local/lib/node_modules/ursa-optional/rebuild.js:13:10)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:283:19)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ursa-optional@0.10.1 install: `node rebuild.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ursa-optional@0.10.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

```

**Comment by rzr** [comment]
Yes I have this Pending PR try it  and comment:
https://github.com/JoshKaufman/ursa/issues/175

Is this package still maintained ? If not please consider:
https://abandonware.github.io/ 

Relate-to: https://github.com/abandonware/abandonware.github.io/issues/5
