### ISSUE TITLE
node-gyp build failed

### ISSUE THREAD

**Issue by GHNewbiee** [quartzjer/ursa#173]
Hi,

This is what I get on the screen:
```
> ursa@0.9.4 install /usr/lib/node_modules/ursa
> node-gyp rebuild

make: Entering directory '/usr/lib/node_modules/ursa/build'
  CXX(target) Release/obj.target/ursaNative/src/ursaNative.o
../src/ursaNative.cc: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE RsaWrap::OpenPublicSshKey(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/ursaNative.cc:389:13: error: invalid use of incomplete type ‘RSA {aka struct rsa_st}’
     obj->rsa->n = BN_bin2bn(data_n, n_length, NULL);
             ^
In file included from /home/xxxxxx/.node-gyp/10.5.0/include/node/openssl/crypto.h:31:0,
                 from /home/xxxxxx/.node-gyp/10.5.0/include/node/openssl/bio.h:20,
                 from /home/xxxxxx/.node-gyp/10.5.0/include/node/openssl/asn1.h:16,
                 from /home/xxxxxx/.node-gyp/10.5.0/include/node/openssl/rsa.h:16,
                 from ../src/ursaNative.h:13,
                 from ../src/ursaNative.cc:3:
/home/xxxxxx/.node-gyp/10.5.0/include/node/openssl/ossl_typ.h:110:16: note: forward declaration of ‘RSA {aka struct rsa_st}’
 typedef struct rsa_st RSA;
                ^
../src/ursaNative.cc:390:13: error: invalid use of incomplete type ‘RSA {aka struct rsa_st}’
     obj->rsa->e = BN_bin2bn(data_e, e_length, NULL);
             ^
In file included from /home/xxxxxx/.node-gyp/10.5.0/include/node/openssl/crypto.h:31:0,
                 from /home/xxxxxx/.node-gyp/10.5.0/include/node/openssl/bio.h:20,
                 from /home/xxxxxx/.node-gyp/10.5.0/include/node/openssl/asn1.h:16,
                 from /home/xxxxxx/.node-gyp/10.5.0/include/node/openssl/rsa.h:16,
                 from ../src/ursaNative.h:13,
                 from ../src/ursaNative.cc:3:
/home/xxxxxx/.node-gyp/10.5.0/include/node/openssl/ossl_typ.h:110:16: note: forward declaration of ‘RSA {aka struct rsa_st}’
 typedef struct rsa_st RSA;
                ^
../src/ursaNative.cc: In static member function ‘static RsaWrap* RsaWrap::expectPrivateKey(RsaWrap*)’:
../src/ursaNative.cc:407:35: error: invalid use of incomplete type ‘RSA {aka struct rsa_st}’
     if ((obj == NULL) || (obj->rsa->d != NULL)) {
                                   ^
In file included from /home/xxxxxx/.node-gyp/10.5.0/include/node/openssl/crypto.h:31:0,
                 from /home/xxxxxx/.node-gyp/10.5.0/include/node/openssl/bio.h:20,
                 from /home/xxxxxx/.node-gyp/10.5.0/include/node/openssl/asn1.h:16,
                 from /home/xxxxxx/.node-gyp/10.5.0/include/node/openssl/rsa.h:16,
                 from ../src/ursaNative.h:13,
                 from ../src/ursaNative.cc:3:
/home/xxxxxx/.node-gyp/10.5.0/include/node/openssl/ossl_typ.h:110:16: note: forward declaration of ‘RSA {aka struct rsa_st}’
 typedef struct rsa_st RSA;
                ^
../src/ursaNative.cc: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE RsaWrap::GetExponent(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/ursaNative.cc:536:34: error: invalid use of incomplete type ‘RSA {aka struct rsa_st}’
     bignumToBuffer(args, obj->rsa->e);
                                  ^
In file included from /home/xxxxxx/.node-gyp/10.5.0/include/node/openssl/crypto.h:31:0,
                 from /home/xxxxxx/.node-gyp/10.5.0/include/node/openssl/bio.h:20,
                 from /home/xxxxxx/.node-gyp/10.5.0/include/node/openssl/asn1.h:16,
                 from /home/xxxxxx/.node-gyp/10.5.0/include/node/openssl/rsa.h:16,
                 from ../src/ursaNative.h:13,
                 from ../src/ursaNative.cc:3:
/home/xxxxxx/.node-gyp/10.5.0/include/node/openssl/ossl_typ.h:110:16: note: forward declaration of ‘RSA {aka struct rsa_st}’
 typedef struct rsa_st RSA;
                ^
../src/ursaNative.cc: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE RsaWrap::GetPrivateExponent(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/ursaNative.cc:552:34: error: invalid use of incomplete type ‘RSA {aka struct rsa_st}’
     bignumToBuffer(args, obj->rsa->d);
                                  ^
In file included from /home/xxxxxx/.node-gyp/10.5.0/include/node/openssl/crypto.h:31:0,
                 from /home/xxxxxx/.node-gyp/10.5.0/include/node/openssl/bio.h:20,
                 from /home/xxxxxx/.node-gyp/10.5.0/include/node/openssl/asn1.h:16,
                 from /home/xxxxxx/.node-gyp/10.5.0/include/node/openssl/rsa.h:16,
                 from ../src/ursaNative.h:13,
                 from ../src/ursaNative.cc:3:
/home/xxxxxx/.node-gyp/10.5.0/include/node/openssl/ossl_typ.h:110:16: note: forward declaration of ‘RSA {aka struct rsa_st}’
 typedef struct rsa_st RSA;
                ^
../src/ursaNative.cc: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE RsaWrap::GetModulus(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/ursaNative.cc:567:34: error: invalid use of incomplete type ‘RSA {aka struct rsa_st}’
     bignumToBuffer(args, obj->rsa->n);
                                  ^
In file included from /home/xxxxxx/.node-gyp/10.5.0/include/node/openssl/crypto.h:31:0,
                 from /home/xxxxxx/.node-gyp/10.5.0/include/node/openssl/bio.h:20,
                 from /home/xxxxxx/.node-gyp/10.5.0/include/node/openssl/asn1.h:16,
                 from /home/xxxxxx/.node-gyp/10.5.0/include/node/openssl/rsa.h:16,
                 from ../src/ursaNative.h:13,
                 from ../src/ursaNative.cc:3:
/home/xxxxxx/.node-gyp/10.5.0/include/node/openssl/ossl_typ.h:110:16: note: forward declaration of ‘RSA {aka struct rsa_st}’
 typedef struct rsa_st RSA;
                ^
../src/ursaNative.cc: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE RsaWrap::CreatePrivateKeyFromComponents(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/ursaNative.cc:1218:17: error: invalid use of incomplete type ‘RSA {aka struct rsa_st}’
         obj->rsa->n = modulus;
                 ^
In file included from /home/xxxxxx/.node-gyp/10.5.0/include/node/openssl/crypto.h:31:0,
                 from /home/xxxxxx/.node-gyp/10.5.0/include/node/openssl/bio.h:20,
                 from /home/xxxxxx/.node-gyp/10.5.0/include/node/openssl/asn1.h:16,
                 from /home/xxxxxx/.node-gyp/10.5.0/include/node/openssl/rsa.h:16,
                 from ../src/ursaNative.h:13,
                 from ../src/ursaNative.cc:3:
/home/xxxxxx/.node-gyp/10.5.0/include/node/openssl/ossl_typ.h:110:16: note: forward declaration of ‘RSA {aka struct rsa_st}’
 typedef struct rsa_st RSA;
                ^
../src/ursaNative.cc:1219:17: error: invalid use of incomplete type ‘RSA {aka struct rsa_st}’
         obj->rsa->e = exponent;
                 ^
In file included from /home/xxxxxx/.node-gyp/10.5.0/include/node/openssl/crypto.h:31:0,
                 from /home/xxxxxx/.node-gyp/10.5.0/include/node/openssl/bio.h:20,
                 from /home/xxxxxx/.node-gyp/10.5.0/include/node/openssl/asn1.h:16,
                 from /home/xxxxxx/.node-gyp/10.5.0/include/node/openssl/rsa.h:16,
                 from ../src/ursaNative.h:13,
                 from ../src/ursaNative.cc:3:
/home/xxxxxx/.node-gyp/10.5.0/include/node/openssl/ossl_typ.h:110:16: note: forward declaration of ‘RSA {aka struct rsa_st}’
 typedef struct rsa_st RSA;
                ^
../src/ursaNative.cc:1220:17: error: invalid use of incomplete type ‘RSA {aka struct rsa_st}’
         obj->rsa->p = p;
                 ^
In file included from /home/xxxxxx/.node-gyp/10.5.0/include/node/openssl/crypto.h:31:0,
                 from /home/xxxxxx/.node-gyp/10.5.0/include/node/openssl/bio.h:20,
                 from /home/xxxxxx/.node-gyp/10.5.0/include/node/openssl/asn1.h:16,
                 from /home/xxxxxx/.node-gyp/10.5.0/include/node/openssl/rsa.h:16,
                 from ../src/ursaNative.h:13,
                 from ../src/ursaNative.cc:3:
/home/xxxxxx/.node-gyp/10.5.0/include/node/openssl/ossl_typ.h:110:16: note: forward declaration of ‘RSA {aka struct rsa_st}’
 typedef struct rsa_st RSA;
                ^
../src/ursaNative.cc:1221:17: error: invalid use of incomplete type ‘RSA {aka struct rsa_st}’
         obj->rsa->q = q;
                 ^
In file included from /home/xxxxxx/.node-gyp/10.5.0/include/node/openssl/crypto.h:31:0,
                 from /home/xxxxxx/.node-gyp/10.5.0/include/node/openssl/bio.h:20,
                 from /home/xxxxxx/.node-gyp/10.5.0/include/node/openssl/asn1.h:16,
                 from /home/xxxxxx/.node-gyp/10.5.0/include/node/openssl/rsa.h:16,
                 from ../src/ursaNative.h:13,
                 from ../src/ursaNative.cc:3:
/home/xxxxxx/.node-gyp/10.5.0/include/node/openssl/ossl_typ.h:110:16: note: forward declaration of ‘RSA {aka struct rsa_st}’
 typedef struct rsa_st RSA;
                ^
../src/ursaNative.cc:1222:17: error: invalid use of incomplete type ‘RSA {aka struct rsa_st}’
         obj->rsa->dmp1 = dp;
                 ^
In file included from /home/xxxxxx/.node-gyp/10.5.0/include/node/openssl/crypto.h:31:0,
                 from /home/xxxxxx/.node-gyp/10.5.0/include/node/openssl/bio.h:20,
                 from /home/xxxxxx/.node-gyp/10.5.0/include/node/openssl/asn1.h:16,
                 from /home/xxxxxx/.node-gyp/10.5.0/include/node/openssl/rsa.h:16,
                 from ../src/ursaNative.h:13,
                 from ../src/ursaNative.cc:3:
/home/xxxxxx/.node-gyp/10.5.0/include/node/openssl/ossl_typ.h:110:16: note: forward declaration of ‘RSA {aka struct rsa_st}’
 typedef struct rsa_st RSA;
                ^
../src/ursaNative.cc:1223:17: error: invalid use of incomplete type ‘RSA {aka struct rsa_st}’
         obj->rsa->dmq1 = dq;
                 ^
In file included from /home/xxxxxx/.node-gyp/10.5.0/include/node/openssl/crypto.h:31:0,
                 from /home/xxxxxx/.node-gyp/10.5.0/include/node/openssl/bio.h:20,
                 from /home/xxxxxx/.node-gyp/10.5.0/include/node/openssl/asn1.h:16,
                 from /home/xxxxxx/.node-gyp/10.5.0/include/node/openssl/rsa.h:16,
                 from ../src/ursaNative.h:13,
                 from ../src/ursaNative.cc:3:
/home/xxxxxx/.node-gyp/10.5.0/include/node/openssl/ossl_typ.h:110:16: note: forward declaration of ‘RSA {aka struct rsa_st}’
 typedef struct rsa_st RSA;
                ^
../src/ursaNative.cc:1224:17: error: invalid use of incomplete type ‘RSA {aka struct rsa_st}’
         obj->rsa->iqmp = inverseQ;
                 ^
In file included from /home/xxxxxx/.node-gyp/10.5.0/include/node/openssl/crypto.h:31:0,
                 from /home/xxxxxx/.node-gyp/10.5.0/include/node/openssl/bio.h:20,
                 from /home/xxxxxx/.node-gyp/10.5.0/include/node/openssl/asn1.h:16,
                 from /home/xxxxxx/.node-gyp/10.5.0/include/node/openssl/rsa.h:16,
                 from ../src/ursaNative.h:13,
                 from ../src/ursaNative.cc:3:
/home/xxxxxx/.node-gyp/10.5.0/include/node/openssl/ossl_typ.h:110:16: note: forward declaration of ‘RSA {aka struct rsa_st}’
 typedef struct rsa_st RSA;
                ^
../src/ursaNative.cc:1225:17: error: invalid use of incomplete type ‘RSA {aka struct rsa_st}’
         obj->rsa->d = d;
                 ^
In file included from /home/xxxxxx/.node-gyp/10.5.0/include/node/openssl/crypto.h:31:0,
                 from /home/xxxxxx/.node-gyp/10.5.0/include/node/openssl/bio.h:20,
                 from /home/xxxxxx/.node-gyp/10.5.0/include/node/openssl/asn1.h:16,
                 from /home/xxxxxx/.node-gyp/10.5.0/include/node/openssl/rsa.h:16,
                 from ../src/ursaNative.h:13,
                 from ../src/ursaNative.cc:3:
/home/xxxxxx/.node-gyp/10.5.0/include/node/openssl/ossl_typ.h:110:16: note: forward declaration of ‘RSA {aka struct rsa_st}’
 typedef struct rsa_st RSA;
                ^
../src/ursaNative.cc: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE RsaWrap::CreatePublicKeyFromComponents(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/ursaNative.cc:1270:17: error: invalid use of incomplete type ‘RSA {aka struct rsa_st}’
         obj->rsa->n = modulus;
                 ^
In file included from /home/xxxxxx/.node-gyp/10.5.0/include/node/openssl/crypto.h:31:0,
                 from /home/xxxxxx/.node-gyp/10.5.0/include/node/openssl/bio.h:20,
                 from /home/xxxxxx/.node-gyp/10.5.0/include/node/openssl/asn1.h:16,
                 from /home/xxxxxx/.node-gyp/10.5.0/include/node/openssl/rsa.h:16,
                 from ../src/ursaNative.h:13,
                 from ../src/ursaNative.cc:3:
/home/xxxxxx/.node-gyp/10.5.0/include/node/openssl/ossl_typ.h:110:16: note: forward declaration of ‘RSA {aka struct rsa_st}’
 typedef struct rsa_st RSA;
                ^
../src/ursaNative.cc:1271:17: error: invalid use of incomplete type ‘RSA {aka struct rsa_st}’
         obj->rsa->e = exponent;
                 ^
In file included from /home/xxxxxx/.node-gyp/10.5.0/include/node/openssl/crypto.h:31:0,
                 from /home/xxxxxx/.node-gyp/10.5.0/include/node/openssl/bio.h:20,
                 from /home/xxxxxx/.node-gyp/10.5.0/include/node/openssl/asn1.h:16,
                 from /home/xxxxxx/.node-gyp/10.5.0/include/node/openssl/rsa.h:16,
                 from ../src/ursaNative.h:13,
                 from ../src/ursaNative.cc:3:
/home/xxxxxx/.node-gyp/10.5.0/include/node/openssl/ossl_typ.h:110:16: note: forward declaration of ‘RSA {aka struct rsa_st}’
 typedef struct rsa_st RSA;
                ^
ursaNative.target.mk:97: recipe for target 'Release/obj.target/ursaNative/src/ursaNative.o' failed
make: *** [Release/obj.target/ursaNative/src/ursaNative.o] Error 1
make: Leaving directory '/usr/lib/node_modules/ursa/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:237:12)
gyp ERR! System Linux 4.15.0-23-generic
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/lib/node_modules/ursa
gyp ERR! node -v v10.5.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ursa@0.9.4 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ursa@0.9.4 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/xxxxxx/.npm/_logs/2018-06-29T10_06_07_716Z-debug.log
```

* **Node Version**: v10.5.0
* **npm Version**: 6.1.0
* **Platform**: LinuxMint 18.3 64-bit
* **Compiler**: 
* **Module**: ursa

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node',
1 verbose cli   '/usr/bin/npm',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'ursa',
1 verbose cli   '--allow-root' ]
2 info using npm@6.1.0
3 info using node@v10.5.0
4 verbose npm-session d130af0b596491f7
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 http fetch GET 304 https://registry.npmjs.org/ursa 235ms (from cache)
8 silly pacote tag manifest for ursa@latest fetched in 257ms
9 timing stage:loadCurrentTree Completed in 574ms
10 silly install loadIdealTree
11 silly install cloneCurrentTreeToIdealTree
12 timing stage:loadIdealTree:cloneCurrentTree Completed in 0ms
13 silly install loadShrinkwrap
14 timing stage:loadIdealTree:loadShrinkwrap Completed in 3ms
15 silly install loadAllDepsIntoIdealTree
16 silly resolveWithNewModule ursa@0.9.4 checking installable status
17 http fetch GET 304 https://registry.npmjs.org/bindings 63ms (from cache)
18 silly pacote range manifest for bindings@^1.2.1 fetched in 66ms
19 silly resolveWithNewModule bindings@1.3.0 checking installable status
20 http fetch GET 304 https://registry.npmjs.org/nan 114ms (from cache)
21 silly pacote range manifest for nan@^2.3.3 fetched in 119ms
22 silly resolveWithNewModule nan@2.10.0 checking installable status
23 timing stage:loadIdealTree:loadAllDepsIntoIdealTree Completed in 136ms
24 timing stage:loadIdealTree Completed in 143ms
25 silly currentTree lib
26 silly idealTree lib
26 silly idealTree └─┬ ursa@0.9.4
26 silly idealTree   ├── bindings@1.3.0
26 silly idealTree   └── nan@2.10.0
27 silly install generateActionsToTake
28 timing stage:generateActionsToTake Completed in 8ms
29 silly diffTrees action count 3
30 silly diffTrees add bindings@1.3.0
31 silly diffTrees add nan@2.10.0
32 silly diffTrees add ursa@0.9.4
33 silly decomposeActions action count 24
34 silly decomposeActions fetch bindings@1.3.0
35 silly decomposeActions extract bindings@1.3.0
36 silly decomposeActions preinstall bindings@1.3.0
37 silly decomposeActions build bindings@1.3.0
38 silly decomposeActions install bindings@1.3.0
39 silly decomposeActions postinstall bindings@1.3.0
40 silly decomposeActions finalize bindings@1.3.0
41 silly decomposeActions refresh-package-json bindings@1.3.0
42 silly decomposeActions fetch nan@2.10.0
43 silly decomposeActions extract nan@2.10.0
44 silly decomposeActions preinstall nan@2.10.0
45 silly decomposeActions build nan@2.10.0
46 silly decomposeActions install nan@2.10.0
47 silly decomposeActions postinstall nan@2.10.0
48 silly decomposeActions finalize nan@2.10.0
49 silly decomposeActions refresh-package-json nan@2.10.0
50 silly decomposeActions fetch ursa@0.9.4
51 silly decomposeActions extract ursa@0.9.4
52 silly decomposeActions preinstall ursa@0.9.4
53 silly decomposeActions build ursa@0.9.4
54 silly decomposeActions install ursa@0.9.4
55 silly decomposeActions postinstall ursa@0.9.4
56 silly decomposeActions finalize ursa@0.9.4
57 silly decomposeActions refresh-package-json ursa@0.9.4
58 silly install executeActions
59 silly doSerial global-install 24
60 verbose correctMkdir /home/xxxxxx/.npm/_locks correctMkdir not in flight; initializing
61 verbose lock using /home/xxxxxx/.npm/_locks/staging-a072192f34a17023.lock for /usr/lib/node_modules/.staging
62 silly doParallel extract 3
63 silly extract bindings@1.3.0
64 silly extract nan@2.10.0
65 silly extract ursa@0.9.4
66 silly tarball trying bindings@^1.2.1 by hash: sha512-DpLh5EzMR2kzvX1KIlVC0VkC3iZtHKTgdtZ0a3pglBZdaQFjt5S9g9xd1lE+YvXyfd6mtCeRnrUfOLYiTMlNSw==
67 silly tarball trying nan@^2.3.3 by hash: sha512-bAdJv7fBLhWC+/Bls0Oza+mvTaNQtP+1RyhhhvD95pgUJz6XM5IzgmxOkItJ9tkoCiplvAnXI1tNmmUD/eScyA==
68 silly tarball trying ursa@latest by hash: sha1-Ciq/t9xCZ/czsPjy/H8siV1ApBM=
69 silly extract bindings@^1.2.1 extracted to /usr/lib/node_modules/.staging/bindings-3a1a9fdd (64ms)
70 silly extract ursa@latest extracted to /usr/lib/node_modules/.staging/ursa-680fd96c (74ms)
71 silly extract nan@^2.3.3 extracted to /usr/lib/node_modules/.staging/nan-325009a3 (88ms)
72 timing action:extract Completed in 94ms
73 silly doReverseSerial unbuild 24
74 silly doSerial remove 24
75 silly doSerial move 24
76 silly doSerial finalize 24
77 silly finalize /usr/lib/node_modules/ursa/node_modules/bindings
78 silly finalize /usr/lib/node_modules/ursa/node_modules/nan
79 silly finalize /usr/lib/node_modules/ursa
80 timing action:finalize Completed in 20ms
81 silly doParallel refresh-package-json 3
82 silly refresh-package-json /usr/lib/node_modules/ursa/node_modules/bindings
83 silly refresh-package-json /usr/lib/node_modules/ursa/node_modules/nan
84 silly refresh-package-json /usr/lib/node_modules/ursa
85 timing action:refresh-package-json Completed in 35ms
86 silly doParallel preinstall 3
87 silly preinstall bindings@1.3.0
88 info lifecycle bindings@1.3.0~preinstall: bindings@1.3.0
89 silly preinstall nan@2.10.0
90 info lifecycle nan@2.10.0~preinstall: nan@2.10.0
91 silly preinstall ursa@0.9.4
92 info lifecycle ursa@0.9.4~preinstall: ursa@0.9.4
93 timing action:preinstall Completed in 3ms
94 silly doSerial build 24
95 silly build bindings@1.3.0
96 info linkStuff bindings@1.3.0
97 silly linkStuff bindings@1.3.0 has /usr/lib/node_modules/ursa/node_modules as its parent node_modules
98 silly linkStuff bindings@1.3.0 is part of a global install
99 silly linkStuff bindings@1.3.0 is installed into a global node_modules
100 silly build nan@2.10.0
101 info linkStuff nan@2.10.0
102 silly linkStuff nan@2.10.0 has /usr/lib/node_modules/ursa/node_modules as its parent node_modules
103 silly linkStuff nan@2.10.0 is part of a global install
104 silly linkStuff nan@2.10.0 is installed into a global node_modules
105 silly build ursa@0.9.4
106 info linkStuff ursa@0.9.4
107 silly linkStuff ursa@0.9.4 has /usr/lib/node_modules as its parent node_modules
108 silly linkStuff ursa@0.9.4 is part of a global install
109 silly linkStuff ursa@0.9.4 is installed into a global node_modules
110 silly linkStuff ursa@0.9.4 is installed into the top-level global node_modules
111 timing action:build Completed in 3ms
112 silly doSerial global-link 24
113 silly doParallel update-linked 0
114 silly doSerial install 24
115 silly install bindings@1.3.0
116 info lifecycle bindings@1.3.0~install: bindings@1.3.0
117 silly install nan@2.10.0
118 info lifecycle nan@2.10.0~install: nan@2.10.0
119 silly install ursa@0.9.4
120 info lifecycle ursa@0.9.4~install: ursa@0.9.4
121 verbose lifecycle ursa@0.9.4~install: unsafe-perm in lifecycle false
122 verbose lifecycle ursa@0.9.4~install: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/usr/lib/node_modules/ursa/node_modules/.bin:/usr/lib/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin
123 verbose lifecycle ursa@0.9.4~install: CWD: /usr/lib/node_modules/ursa
124 silly lifecycle ursa@0.9.4~install: Args: [ '-c', 'node-gyp rebuild' ]
125 silly lifecycle ursa@0.9.4~install: Returned: code: 1  signal: null
126 info lifecycle ursa@0.9.4~install: Failed to exec install script
127 timing action:install Completed in 616ms
128 verbose unlock done using /home/xxxxxx/.npm/_locks/staging-a072192f34a17023.lock for /usr/lib/node_modules/.staging
129 timing stage:rollbackFailedOptional Completed in 49ms
130 timing stage:runTopLevelLifecycles Completed in 1563ms
131 verbose stack Error: ursa@0.9.4 install: `node-gyp rebuild`
131 verbose stack Exit status 1
131 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:304:16)
131 verbose stack     at EventEmitter.emit (events.js:182:13)
131 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
131 verbose stack     at ChildProcess.emit (events.js:182:13)
131 verbose stack     at maybeClose (internal/child_process.js:961:16)
131 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:5)
132 verbose pkgid ursa@0.9.4
134 verbose Linux 4.15.0-23-generic
135 verbose argv "/usr/bin/node" "/usr/bin/npm" "install" "-g" "ursa" "--allow-root"
136 verbose node v10.5.0
137 verbose npm  v6.1.0
138 error code ELIFECYCLE
139 error errno 1
140 error ursa@0.9.4 install: `node-gyp rebuild`
140 error Exit status 1
141 error Failed at the ursa@0.9.4 install script.
141 error This is probably not a problem with npm. There is likely additional logging output above.
142 verbose exit [ 1, true ]
```

Tia

**Comment by mattcollier** [comment]
@GHNewbiee I have found that that master builds properly on node v10.6.0.

**Comment by rzr** [comment]
I confirm for node v8.11.3 worked too, just use:

    npm install git+https://github.com/jkuri/ursa.git

Until package is released on npm.org ( https://github.com/JoshKaufman/ursa/issues/172 )
