### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by FunnyCheese** [quartzjer/ursa#176]
root@mrcheezezs:~/bot# npm install ursa

> ursa@0.9.4 install /root/bot/node_modules/ursa
> node-gyp rebuild

gyp ERR! build error
gyp ERR! stack Error: not found: make
gyp ERR! stack     at getNotFoundError (/usr/lib/node_modules/npm/node_modules/which/which.js:13:12)
gyp ERR! stack     at F (/usr/lib/node_modules/npm/node_modules/which/which.js:68:19)
gyp ERR! stack     at E (/usr/lib/node_modules/npm/node_modules/which/which.js:80:29)
gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/which/which.js:89:16
gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/which/node_modules/isexe/index.js:42:5
gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/which/node_modules/isexe/mode.js:8:5
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:152:21)
gyp ERR! System Linux 2.6.32-042stab127.2
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /root/bot/node_modules/ursa
gyp ERR! node -v v8.11.3
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm WARN enoent ENOENT: no such file or directory, open '/root/bot/package.json'
npm WARN bot No description
npm WARN bot No repository field.
npm WARN bot No README data
npm WARN bot No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ursa@0.9.4 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ursa@0.9.4 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-08-11T16_14_28_620Z-debug.log

**Comment by FunnyCheese** [comment]
root@mrcheezezs:~/bot# node -v
v8.11.3

**Comment by rzr** [comment]
just install gnu make 1st and try again

**Comment by rgomids** [comment]
Hi man.
Try this:
- Remove ~/.node-gyp
- Install and set node LTS (v8.11.4)
- Try to install ursa.

This worked for me

**Comment by chrisengelsma** [comment]
This worked for me, thanks

**Comment by gitowiec** [comment]
on Ubuntu 18.04 `sudo apt-get install build-essential g++` worked for me

**Comment by rzr** [comment]
So I guess this bug can or should be closed, or should readme be updated ?

**Comment by Norfeldt** [comment]
I'm also having trouble installing it (node v10.14.2) on my mac. Any suggestions?

**Comment by hikmawanaz** [comment]
> I'm also having trouble installing it (node v10.14.2) on my mac. Any suggestions?

 i also have same issue on mac 10.13 with
node -v v10.15.3
do you have any solution?

**Comment by rzr** [comment]
may you submit to change to make CI Failing on specific configs ?

**Comment by coolaj86** [comment]
Unless you're using an older version of node that's supported by ursa you may want to consider using node's built-in RSA support and lightweight JWK<->PEM conversion.

## Node v10+ has Native RSA Support now

* `crypto.generateKeyPair()` 
  * https://nodejs.org/api/crypto.html#crypto_crypto_generatekeypair_type_options_callback
* `Rasha.generate()` (RSA + PEM<->JWK)
  * https://git.coolaj86.com/coolaj86/keypairs.js/
* `Keypairs.generate()` (RSA/ECDSA + PEM<->JWK)
  * https://git.coolaj86.com/coolaj86/rasha.js/
