### ISSUE TITLE
Building on windows 10 fails

### ISSUE THREAD

**Issue by tinytinysun** [quartzjer/ursa#181]
d:\workspace\muzhibuluo\dianziyan>npm install

> ursa@0.9.4 install d:\workspace\muzhibuluo\dianziyan\node_modules\ursa
> node-gyp rebuild

d:\workspace\muzhibuluo\dianziyan\node_modules\ursa>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
在此解决方案中一次生成一个项目。若要启用并行生成，请添加“/m”开关。
  ursaNative.cc
  win_delay_load_hook.cc
..\src\ursaNative.cc(157): warning C4244: “参数”: 从“ssize_t”转换到“int”，可能丢失数据 [d:\workspace\muzhibuluo\dianziyan\node_modul
es\ursa\build\ursaNative.vcxproj]
..\src\ursaNative.cc(172): warning C4244: “参数”: 从“ssize_t”转换到“int”，可能丢失数据 [d:\workspace\muzhibuluo\dianziyan\node_modul
es\ursa\build\ursaNative.vcxproj]
C:\Users\tinytinysun\.node-gyp\8.9.1\x64\node.lib : fatal error LNK1106: 文件无效或磁盘已满: 无法查找到 0x1F84E8 [d:\workspace\muzhib
uluo\dianziyan\node_modules\ursa\build\ursaNative.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd d:\workspace\muzhibuluo\dianziyan\node_modules\ursa
gyp ERR! node -v v8.9.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ursa@0.9.4 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ursa@0.9.4 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\tinytinysun\AppData\Roaming\npm-cache\_logs\2018-11-15T15_52_39_869Z-debug.log

**Comment by echarrod** [comment]
Have you tried with the `--msvs_version=2015` flag? So `npm install -g ursa --msvs_version=2015`

If not, there are a lot of good suggestions here - https://github.com/Microsoft/nodejs-guidelines/blob/7d09d467d6fb5477f0e875c130766a625d9fe293/windows-environment.md

**Comment by coolaj86** [comment]
Unless you're using an older version of node that's supported by ursa you may want to consider using node's built-in RSA support and lightweight JWK<->PEM conversion.

## Node v10+ has Native RSA Support now

* `crypto.generateKeyPair()` 
  * https://nodejs.org/api/crypto.html#crypto_crypto_generatekeypair_type_options_callback
* `Rasha.generate()` (RSA + PEM<->JWK)
  * https://git.coolaj86.com/coolaj86/keypairs.js/
* `Keypairs.generate()` (RSA/ECDSA + PEM<->JWK)
  * https://git.coolaj86.com/coolaj86/rasha.js/
