### ISSUE TITLE
Node v0.11.13, errors on install

### ISSUE THREAD

**Issue by merqlove** [quartzjer/ursa#64]
#46
Because this issue we made our own RSA lib for chef-api package.
https://github.com/mal/forsake

```
> ursa@0.8.1 install /Users/.../Repo/.../test/visual-chef/src/node_modules/ursa
> node-gyp configure && node-gyp build && node install.js

  CXX(target) Release/obj.target/ursaNative/src/ursaNative.o
In file included from ../src/ursaNative.cc:3:
../src/ursaNative.h:14:23: error: expected class name
class RsaWrap : node::ObjectWrap {
                      ^
../src/ursaNative.h:22:44: error: no type named 'Arguments' in namespace 'v8'; did you mean 'v8::internal::Arguments'?
    static v8::Handle<v8::Value> New(const v8::Arguments& args);
                                           ^~~~~~~~~~~~~
                                           v8::internal::Arguments
/Users/.../.node-gyp/0.11.13/deps/v8/include/v8.h:149:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
In file included from ../src/ursaNative.cc:3:
../src/ursaNative.h:23:59: error: no type named 'Arguments' in namespace 'v8'; did you mean 'v8::internal::Arguments'?
    static v8::Handle<v8::Value> GeneratePrivateKey(const v8::Arguments& args);
                                                          ^~~~~~~~~~~~~
                                                          v8::internal::Arguments
/Users/.../.node-gyp/0.11.13/deps/v8/include/v8.h:149:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
In file included from ../src/ursaNative.cc:3:
../src/ursaNative.h:24:52: error: no type named 'Arguments' in namespace 'v8'; did you mean 'v8::internal::Arguments'?
    static v8::Handle<v8::Value> GetExponent(const v8::Arguments& args);
                                                   ^~~~~~~~~~~~~
                                                   v8::internal::Arguments
/Users/.../.node-gyp/0.11.13/deps/v8/include/v8.h:149:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
In file included from ../src/ursaNative.cc:3:
../src/ursaNative.h:25:51: error: no type named 'Arguments' in namespace 'v8'; did you mean 'v8::internal::Arguments'?
    static v8::Handle<v8::Value> GetModulus(const v8::Arguments& args);
                                                  ^~~~~~~~~~~~~
                                                  v8::internal::Arguments
/Users/.../.node-gyp/0.11.13/deps/v8/include/v8.h:149:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
In file included from ../src/ursaNative.cc:3:
../src/ursaNative.h:26:57: error: no type named 'Arguments' in namespace 'v8'; did you mean 'v8::internal::Arguments'?
    static v8::Handle<v8::Value> GetPrivateKeyPem(const v8::Arguments& args);
                                                        ^~~~~~~~~~~~~
                                                        v8::internal::Arguments
/Users/.../.node-gyp/0.11.13/deps/v8/include/v8.h:149:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
In file included from ../src/ursaNative.cc:3:
../src/ursaNative.h:27:56: error: no type named 'Arguments' in namespace 'v8'; did you mean 'v8::internal::Arguments'?
    static v8::Handle<v8::Value> GetPublicKeyPem(const v8::Arguments& args);
                                                       ^~~~~~~~~~~~~
                                                       v8::internal::Arguments
/Users/.../.node-gyp/0.11.13/deps/v8/include/v8.h:149:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
In file included from ../src/ursaNative.cc:3:
../src/ursaNative.h:28:55: error: no type named 'Arguments' in namespace 'v8'; did you mean 'v8::internal::Arguments'?
    static v8::Handle<v8::Value> PrivateDecrypt(const v8::Arguments& args);
                                                      ^~~~~~~~~~~~~
                                                      v8::internal::Arguments
/Users/.../.node-gyp/0.11.13/deps/v8/include/v8.h:149:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
In file included from ../src/ursaNative.cc:3:
../src/ursaNative.h:29:55: error: no type named 'Arguments' in namespace 'v8'; did you mean 'v8::internal::Arguments'?
    static v8::Handle<v8::Value> PrivateEncrypt(const v8::Arguments& args);
                                                      ^~~~~~~~~~~~~
                                                      v8::internal::Arguments
/Users/.../.node-gyp/0.11.13/deps/v8/include/v8.h:149:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
In file included from ../src/ursaNative.cc:3:
../src/ursaNative.h:30:54: error: no type named 'Arguments' in namespace 'v8'; did you mean 'v8::internal::Arguments'?
    static v8::Handle<v8::Value> PublicDecrypt(const v8::Arguments& args);
                                                     ^~~~~~~~~~~~~
                                                     v8::internal::Arguments
/Users/.../.node-gyp/0.11.13/deps/v8/include/v8.h:149:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
In file included from ../src/ursaNative.cc:3:
../src/ursaNative.h:31:54: error: no type named 'Arguments' in namespace 'v8'; did you mean 'v8::internal::Arguments'?
    static v8::Handle<v8::Value> PublicEncrypt(const v8::Arguments& args);
                                                     ^~~~~~~~~~~~~
                                                     v8::internal::Arguments
/Users/mrcr/.node-gyp/0.11.13/deps/v8/include/v8.h:149:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
In file included from ../src/ursaNative.cc:3:
../src/ursaNative.h:32:57: error: no type named 'Arguments' in namespace 'v8'; did you mean 'v8::internal::Arguments'?
    static v8::Handle<v8::Value> SetPrivateKeyPem(const v8::Arguments& args);
                                                        ^~~~~~~~~~~~~
                                                        v8::internal::Arguments
/Users/.../.node-gyp/0.11.13/deps/v8/include/v8.h:149:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
In file included from ../src/ursaNative.cc:3:
../src/ursaNative.h:33:56: error: no type named 'Arguments' in namespace 'v8'; did you mean 'v8::internal::Arguments'?
    static v8::Handle<v8::Value> SetPublicKeyPem(const v8::Arguments& args);
                                                       ^~~~~~~~~~~~~
                                                       v8::internal::Arguments
/Users/.../.node-gyp/0.11.13/deps/v8/include/v8.h:149:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
In file included from ../src/ursaNative.cc:3:
../src/ursaNative.h:34:45: error: no type named 'Arguments' in namespace 'v8'; did you mean 'v8::internal::Arguments'?
    static v8::Handle<v8::Value> Sign(const v8::Arguments& args);
                                            ^~~~~~~~~~~~~
                                            v8::internal::Arguments
/Users/.../.node-gyp/0.11.13/deps/v8/include/v8.h:149:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
In file included from ../src/ursaNative.cc:3:
../src/ursaNative.h:35:47: error: no type named 'Arguments' in namespace 'v8'; did you mean 'v8::internal::Arguments'?
    static v8::Handle<v8::Value> Verify(const v8::Arguments& args);
                                              ^~~~~~~~~~~~~
                                              v8::internal::Arguments
/Users/.../.node-gyp/0.11.13/deps/v8/include/v8.h:149:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
In file included from ../src/ursaNative.cc:3:
../src/ursaNative.h:39:50: error: no type named 'Arguments' in namespace 'v8'; did you mean 'v8::internal::Arguments'?
    static RsaWrap *unwrapExpectPrivateKey(const v8::Arguments& args);
                                                 ^~~~~~~~~~~~~
                                                 v8::internal::Arguments
/Users/.../.node-gyp/0.11.13/deps/v8/include/v8.h:149:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
In file included from ../src/ursaNative.cc:3:
../src/ursaNative.h:40:43: error: no type named 'Arguments' in namespace 'v8'; did you mean 'v8::internal::Arguments'?
    static RsaWrap *unwrapExpectSet(const v8::Arguments& args);
                                          ^~~~~~~~~~~~~
                                          v8::internal::Arguments
/Users/.../.node-gyp/0.11.13/deps/v8/include/v8.h:149:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
In file included from ../src/ursaNative.cc:3:
../src/ursaNative.h:41:45: error: no type named 'Arguments' in namespace 'v8'; did you mean 'v8::internal::Arguments'?
    static RsaWrap *unwrapExpectUnset(const v8::Arguments& args);
                                            ^~~~~~~~~~~~~
                                            v8::internal::Arguments
/Users/.../.node-gyp/0.11.13/deps/v8/include/v8.h:149:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
In file included from ../src/ursaNative.cc:3:
../src/ursaNative.h:46:39: error: no type named 'Arguments' in namespace 'v8'; did you mean 'v8::internal::Arguments'?
v8::Handle<v8::Value> TextToNid(const v8::Arguments& args);
                                      ^~~~~~~~~~~~~
                                      v8::internal::Arguments
/Users/.../.node-gyp/0.11.13/deps/v8/include/v8.h:149:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make: *** [Release/obj.target/ursaNative/src/ursaNative.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/.../.nvm/v0.11.13/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1046:12)
gyp ERR! System Darwin 13.4.0
gyp ERR! command "node" "/Users/.../.nvm/v0.11.13/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build"
gyp ERR! cwd /Users/.../Repo/.../test/visual-chef/src/node_modules/ursa
gyp ERR! node -v v0.11.13
gyp ERR! node-gyp -v v1.0.1
gyp ERR! not ok 
```

**Comment by adrai** [comment]
fyi: node 0.12 is released

**Comment by quartzjer** [comment]
I'm going to close this issue now that nan support landed, any new bugs can be new issues :)
