### ISSUE TITLE
ursa build error

### ISSUE THREAD

**Issue by sayume** [quartzjer/ursa#68]
When I run "npm install" on ubuntu machine, I got this error:
$ npm install
npm WARN package.json sdk@0.0.1 No description
npm WARN package.json sdk@0.0.1 No repository field.
npm WARN package.json sdk@0.0.1 No README data
-|/-|/-

> ursa@0.8.1 install /home/liutuo/workspace/chameleon/server/node_modules/ursa
> node-gyp configure && node-gyp build && node install.js

make: Entering directory `/home/liutuo/workspace/chameleon/server/node_modules/ursa/build'
make: *** No rule to make target`../../../../../../../../usr/local/lib/node_modules/npm/node_modules/node-gyp/addon.gypi', needed by `Makefile'.  Stop.
make: Leaving directory`/home/liutuo/workspace/chameleon/server/node_modules/ursa/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:810:12)
gyp ERR! System Linux 3.8.0-19-generic
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build"
gyp ERR! cwd /home/liutuo/workspace/chameleon/server/node_modules/ursa
gyp ERR! node -v v0.10.33
gyp ERR! node-gyp -v v1.0.1
gyp ERR! not ok 

npm ERR! ursa@0.8.1 install: `node-gyp configure && node-gyp build && node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ursa@0.8.1 install script.
npm ERR! This is most likely a problem with the ursa package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp configure && node-gyp build && node install.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls ursa
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 3.8.0-19-generic
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! cwd /home/liutuo/workspace/chameleon/server
npm ERR! node -v v0.10.33
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! not ok code 0

I tried node version 0.8.9, still got the same error, what's the problem with it.

**Comment by quartzjer** [comment]
Could you try the newest version just updated today to see if the new build system helps?

**Comment by norx85** [comment]
I had the same problem on Windows 8.1. The solution was to install the correct architecture of openssl:
x86 openssl if using nodejs x86 and x64 openssl if using nodejs x64
