### ISSUE TITLE
client side encrypt, server side decrypt

### ISSUE THREAD

**Issue by gurumelo** [quartzjer/ursa#69]
Hello, i try to do this:
https://github.com/travist/jsencrypt/blob/master/bin/jsencrypt.js
client side

```
<script src="jquery.min.js"></script>
<script src="jsencrypt.min.js"></script>
<script>
```

// Create the encryption object and set the key.
var crypt = new JSEncrypt();
crypt.setKey('-----BEGIN PUBLIC KEY-----YOUR PUBLIC KEY-----END PUBLIC KEY-----'); //You can use also setPrivateKey and setPublicKey, they are
 both alias to setKey

//Eventhough the methods are called setPublicKey and setPrivateKey, remember
//that they are only alias to setKey, so you can pass them both a private or
//a public openssl key, just remember that setting a public key allows you to only encrypt.

var text = 'test';
// Encrypt the data with the public key.
var enc = crypt.encrypt(text);
alert(enc);

// Now decrypt the crypted text with the private key.

////var dec = crypt.decrypt(enc);

// Now a simple check to see if the round-trip worked.

////if (dec === text){
////    alert('It works!!!');
////} else {
////    alert('Something went wrong....');
////}

```
</script>
```

And the server side:

'use strict';

var fs = require('fs')
  , ursa = require('ursa')
  , crt
  , key
  , msg
  ;

key = ursa.createPrivateKey(fs.readFileSync('./rsapriv.pem'));

msg = 'oDdwc6sYZz1FxpFr/ZumS2rrgkUN38raevlj4iNLDZg6JcQkxB9ARXnhd+Jljx37xgoVcQ+rmDQZQLMVjsFOoSBGjuR+uDnY3V8u+8OQpcODMgNU1nFaqrgt34s904Djf6a9kxqO33CZWg2rCjM+XzA2SlfcH66CiBMhW0
CeB+pPxLN0Hx+pmSzla7+J1B3DG8/Nan9LltzZ8/RdHwks2icWylCbUvRadQamQDUKjhKfPSH4ITLAw9QjJy+qT+GyXvv9JDRBI2WocIcADDRqkJScpw20pJKEz6WC8cs8stSpNrSOebDIj3tnquo0yqa4Ok8AXzakk4lndtBZqPI
JBA==';

console.log('Decrypt with Private');
msg = key.decrypt(msg, 'base64', 'utf8');
console.log(msg);

Error:
        return encodeBuffer(rsa.privateDecrypt(buf, padding), outEncoding);
                                ^
Error: error:0407A079:rsa routines:RSA_padding_check_PKCS1_OAEP:oaep decoding error
    at Object.decrypt (/home/mari/node/jsencrypt/node_modules/ursa/lib/ursa.js:291:33)
    at Object.<anonymous> (/home/mari/node/jsencrypt/server2.js:23:11)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3

thank you

**Comment by weiketa** [comment]
the same problem
