### ISSUE TITLE
Build Error with io.js

### ISSUE THREAD

**Issue by steelbrain** [quartzjer/ursa#83]
```bash
steel@BlackBeauty:/anees/Lab/noxious$ npm install ursa

-
> ursa@0.8.4 install /anees/Lab/noxious/node_modules/ursa
> node-gyp rebuild

gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: 404 status code downloading tarball
gyp ERR! stack     at Request.<anonymous> (/anees/Local/iojs-v1.5.2-nightly20150312e2c9040995-linux-x64/lib/node_modules/npm/node_modules/node-gyp/lib/install.js:246:14)
gyp ERR! stack     at emitOne (events.js:82:20)
gyp ERR! stack     at Request.emit (events.js:166:7)
gyp ERR! stack     at Request.onRequestResponse (/anees/Local/iojs-v1.5.2-nightly20150312e2c9040995-linux-x64/lib/node_modules/npm/node_modules/request/request.js:1176:10)
gyp ERR! stack     at emitOne (events.js:77:13)
gyp ERR! stack     at ClientRequest.emit (events.js:166:7)
gyp ERR! stack     at HTTPParser.parserOnIncomingClient (_http_client.js:410:21)
gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:88:23)
gyp ERR! stack     at TLSSocket.socketOnData (_http_client.js:300:20)
gyp ERR! stack     at emitOne (events.js:77:13)
gyp ERR! System Linux 3.19.0-031900-generic
gyp ERR! command "node" "/anees/Local/iojs-v1.5.2-nightly20150312e2c9040995-linux-x64/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /anees/Lab/noxious/node_modules/ursa
gyp ERR! node -v v1.5.2-nightly20150312e2c9040995
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok 
npm ERR! Linux 3.19.0-031900-generic
npm ERR! argv "/usr/local/bin/iojs" "/usr/local/bin/npm" "install" "ursa"
npm ERR! node v1.5.2-nightly20150312e2c9040995
npm ERR! npm  v2.7.0
npm ERR! code ELIFECYCLE

npm ERR! ursa@0.8.4 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ursa@0.8.4 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the ursa package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls ursa
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /anees/Lab/noxious/npm-debug.log

```

**Comment by steelbrain** [comment]
Nevermind it's an error in `node-gyp`, filed under TooTallNate/node-gyp/issues/563

**Comment by steelbrain** [comment]
Nevermind it's an error in `node-gyp`, filed under TooTallNate/node-gyp/issues/563
