### ISSUE TITLE
Cannot decrypt using PublicKey 

### ISSUE THREAD

**Issue by soheilc** [quartzjer/ursa#88]
Hello
I generate a RSA key from [here](http://travistidwell.com/jsencrypt/demo/) and past them in **public.pem** and **private.pem** files.

```javascript
#!/usr/bin/env node
var ursa = require('ursa'),
      fs = require('fs');

var privateKey = ursa.createPrivateKey(fs.readFileSync('/home/vagrant/openSSL-key/private.pem'));
var publicKey = ursa.createPublicKey(fs.readFileSync('/home/vagrant/openSSL-key/public.pem'));

var text = 'Hello RSA!';
var encrypted = privateKey.encrypt(text, 'utf8', 'base64');
console.log('encrypted: ', encrypted);

var decrypted = publicKey.encrypt(encrypted, 'utf8', 'base64');
console.log('decrypted: ', decrypted);
```

When i run this code i got this Error
```
/var/www/node_modules/ursa/lib/ursa.js:278
        return encodeBuffer(rsa.publicEncrypt(buf, padding), outEncoding);
                                ^
Error: error:0406B06E:rsa routines:RSA_padding_add_none:data too large for key size
    at Object.encrypt (/var/www/node_modules/ursa/lib/ursa.js:278:33)
    at Object.<anonymous> (/var/www/src/farmer-cli.js:14:27)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:902:3
```

**Comment by 4Taine** [comment]
to encrypt with private key an decrypt with the public one, you need to call privateEncrypt with the private key. And publicDecrypt with the public key : 

```javascript
var ursa = require('ursa')
var fs = require('fs');

var privateKey = ursa.createPrivateKey(fs.readFileSync('/home/vagrant/openSSL-key/private.pem'));
var publicKey = ursa.createPublicKey(fs.readFileSync('/home/vagrant/openSSL-key/public.pem'));
var text = 'Hello RSA!';
var encrypted = privateKey.privateEncrypt(text, 'utf8', 'base64');
console.log('encrypted: ', encrypted);

var decrypted = publicKey.publicDecrypt(encrypted,  'base64','utf8');
console.log('decrypted: ', decrypted);
```

**Comment by daddybh** [comment]
hi @lucas-pouchot  I also have the same problem. Here is my code:


```
     Error: error:0406C06E:rsa routines:RSA_padding_add_PKCS1_type_1:data too large for key size
```

```
function encryptWithPrivateKey(toEncrypt, privateKey) {
    if (!toEncrypt) {
        return toEncrypt;
    }
    let key = ursa.createPrivateKey(privateKey);
    let encrypted = key.privateEncrypt(toEncrypt, 'utf8', 'base64');
    return encrypted;
}
```
