### ISSUE TITLE
invalid ELF header with OpenShift Nodejs and node_modules/ursa

### ISSUE THREAD

**Issue by codebased** [quartzjer/ursa#97]
I am using OpenShift for uploading my first node js.

I am finding the following error in my log:

Error: /var/lib/openshift/558e94775973ca43a1000132/app-root/runtime/repo/node_modules/ursa/build/Release/ursaNative.node: invalid ELF header
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at bindings (/var/lib/openshift/558e94775973ca43a1000132/app-root/runtime/repo/node_modules/ursa/node_modules/bindings/bindings.js:76:44)
    at Object.<anonymous> (/var/lib/openshift/558e94775973ca43a1000132/app-root/runtime/repo/node_modules/ursa/lib/ursa.js:18:37)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at new crypto (/var/lib/openshift/558e94775973ca43a1000132/app-root/runtime/repo/utilities/crypto.js:3:16)
    at Object.<anonymous> (/var/lib/openshift/558e94775973ca43a1000132/app-root/runtime/repo/utilities/crypto.js:22:18)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)

can you please tell me what I should with invalid ELF header error.

**Comment by codebased** [comment]
After various attempt, with 0.8.5 and 0.8.4 version, the ursa is throwing the following exception: 

> ursa@0.8.5 install /var/lib/openshift/558e94775973ca43a1000132/app-root/runtime/repo/node_modules/ursa
> node-gyp rebuild

Traceback (most recent call last):
  File "/opt/rh/v8314/root/usr/bin/gyp", line 15, in <module>
    import gyp
ImportError: No module named gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/opt/rh/nodejs010/root/usr/lib/node_modules/node-gyp/lib/configure.js:338:16)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:797:12)
gyp ERR! System Linux 2.6.32-504.16.2.el6.x86_64
gyp ERR! command "node" "/opt/rh/nodejs010/root/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /var/lib/openshift/558e94775973ca43a1000132/app-root/runtime/repo/node_modules/ursa
gyp ERR! node -v v0.10.25
gyp ERR! node-gyp -v v0.12.2
gyp ERR! not ok 
npm ERR! ursa@0.8.5 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ursa@0.8.5 install script.
npm ERR! This is most likely a problem with the ursa package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls ursa
npm ERR! There is likely additional logging output above.

npm ERR! System Linux 2.6.32-504.16.2.el6.x86_64
npm ERR! command "node" "/opt/rh/nodejs010/root/usr/bin/npm" "install"
npm ERR! cwd /var/lib/openshift/558e94775973ca43a1000132/app-root/runtime/repo
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.24
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /var/lib/openshift/558e94775973ca43a1000132/app-root/runtime/repo/npm-debug.log
npm ERR! not ok code 0

**Comment by homfen** [comment]
I have the same error after uploading the code to the server, but it works fine in the local.

**Comment by codebased** [comment]
ended up using https://www.npmjs.com/package/crypto

function crypto() {
    var crypto = require('crypto');
    var algorithm = 'aes-256-ctr', password = '...';
    this.encrypt = encrypt;
    this.decrypt = decrypt;

    function encrypt(data) {
        var cipher = crypto.createCipher(algorithm, password)
        var crypted = cipher.update(data, 'utf8', 'hex')
        crypted += cipher.final('hex');
        return crypted;
    }

    function decrypt(data) {
        var decipher = crypto.createDecipher(algorithm, password)
        var dec = decipher.update(data, 'hex', 'utf8')
        dec += decipher.final('utf8');
        return dec;
    }
}

module.exports = new crypto();
